#!/usr/bin/env bash
# capture.sh — snapshot THIS Arch machine into ./packages, ./dotfiles, ./dconf
# Run on the source machine. Regenerates everything the installer consumes.
# Safe to re-run: it overwrites its own outputs and never touches $HOME.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG="$HERE/packages"
DOT="$HERE/dotfiles"
DCONF="$HERE/dconf"
mkdir -p "$PKG" "$DOT" "$DCONF"

say() { printf '\033[1;34m::\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$*" >&2; }

# ---------------------------------------------------------------------------
# Category map. Package -> category. Anything not listed lands in
# "Uncategorized" so nothing is ever silently dropped.
# ---------------------------------------------------------------------------
declare -A CAT=(
  # Security · recon / scanning
  [nmap]="Security-Recon" [rustscan]="Security-Recon" [bettercap]="Security-Recon"
  [enum4linux]="Security-Recon" [whois]="Security-Recon" [bind]="Security-Recon"
  # Security · web / directory fuzzing
  [ffuf]="Security-Web" [gobuster]="Security-Web" [dirsearch]="Security-Web"
  [nikto]="Security-Web" [wpscan]="Security-Web"
  # Security · password / hash cracking
  [hashcat]="Security-Cracking" [john]="Security-Cracking" [hydra]="Security-Cracking"
  [medusa]="Security-Cracking" [fcrackzip]="Security-Cracking"
  # Security · exploitation / C2 / netcat
  [metasploit]="Security-Exploit" [openbsd-netcat]="Security-Exploit"
  # Security · forensics / stego
  [binwalk]="Security-Forensics" [steghide]="Security-Forensics"
  [stegseek]="Security-Forensics" [perl-image-exiftool]="Security-Forensics"
  # Security · OSINT
  [sherlock]="Security-OSINT"
  # Terminal / CLI tooling
  [git]="Terminal-CLI" [github-cli]="Terminal-CLI" [jq]="Terminal-CLI"
  [tree]="Terminal-CLI" [wget]="Terminal-CLI" [lsof]="Terminal-CLI"
  [man-db]="Terminal-CLI" [7zip]="Terminal-CLI" [neovim]="Terminal-CLI"
  [zsh]="Terminal-CLI" [ghostty]="Terminal-CLI" [rofi]="Terminal-CLI"
  [wofi]="Terminal-CLI" [xclip]="Terminal-CLI" [wl-clipboard]="Terminal-CLI"
  [feh]="Terminal-CLI"
  # Development / containers / languages
  [docker]="Dev-Tools" [docker-compose]="Dev-Tools" [lazydocker]="Dev-Tools"
  [postgresql]="Dev-Tools" [nodejs]="Dev-Tools" [npm]="Dev-Tools"
  [rustup]="Dev-Tools" [gopls]="Dev-Tools" [code]="Dev-Tools"
  [python-pip]="Dev-Tools" [python-requests]="Dev-Tools" [python-termcolor]="Dev-Tools"
  [python-evdev]="Dev-Tools" [cronie]="Dev-Tools"
  # AI / editors / desktop apps
  [obsidian]="Apps" [firefox]="Apps" [google-chrome]="Apps"
  [libreoffice-still]="Apps" [claude-desktop-bin]="Apps" [opencode]="Apps"
  [qwen-code]="Apps" [variety]="Apps" [epiphany]="Apps"
)

# GNOME desktop and system/driver buckets are matched by prefix below, so we
# don't have to enumerate every gnome-* and gvfs-* package by hand.
prefix_cat() {
  case "$1" in
    gnome-*|gdm|nautilus|gst-plugin-pipewire|grilo-plugins|rygel|sushi|yelp|\
    orca|loupe|papers|showtime|snapshot|decibels|baobab|simple-scan|tecla|\
    gnome-menus|xdg-desktop-portal-gnome|xdg-user-dirs-gtk) echo "GNOME-Desktop" ;;
    gvfs*|pipewire*|wireplumber|libpulse|bluez*|networkmanager|network-manager-applet|\
    nftables|nss-mdns|ufw|openvpn|wireguard-tools|linux|linux-firmware|intel-ucode|\
    sof-firmware|efibootmgr|grub|base|base-devel|sudo|zram-generator|gnome-keyring|\
    ydotool|wtype|xdotool|xorg-xrandr|gvfs) echo "System-Base" ;;
    *) echo "" ;;
  esac
}

categorize() {
  local p="$1"
  if [[ -n "${CAT[$p]:-}" ]]; then echo "${CAT[$p]}"; return; fi
  local pc; pc="$(prefix_cat "$p")"
  if [[ -n "$pc" ]]; then echo "$pc"; return; fi
  echo "Uncategorized"
}

# Emit a package list grouped under "## Category" headers. Installer strips '#'.
write_categorized() {
  local outfile="$1"; shift
  local pkgs=("$@")
  declare -A bucket=()
  local p c
  for p in "${pkgs[@]}"; do
    c="$(categorize "$p")"
    bucket[$c]+="$p"$'\n'
  done
  {
    echo "# Generated by capture.sh on $(date -Iseconds)"
    echo "# Lines starting with # are comments; installer ignores them."
    echo
    for c in $(printf '%s\n' "${!bucket[@]}" | sort); do
      echo "## $c"
      printf '%s' "${bucket[$c]}" | sort
      echo
    done
  } > "$outfile"
}

# ---------------------------------------------------------------------------
# 1. Packages
# ---------------------------------------------------------------------------
say "Capturing pacman explicit packages (categorized)…"
# Split explicit packages: native repos vs BlackArch (needs repo bootstrap) vs foreign/AUR.
mapfile -t EXPLICIT < <(pacman -Qqe)
native=(); blackarch=(); foreign=()
mapfile -t FOREIGN_SET < <(pacman -Qqm)
is_foreign() { local x; for x in "${FOREIGN_SET[@]}"; do [[ "$x" == "$1" ]] && return 0; done; return 1; }

for p in "${EXPLICIT[@]}"; do
  if is_foreign "$p"; then
    foreign+=("$p"); continue
  fi
  repo="$(pacman -Si "$p" 2>/dev/null | awk -F': ' '/^Repository/{print $2; exit}')"
  if [[ "$repo" == "blackarch" ]]; then blackarch+=("$p"); else native+=("$p"); fi
done

write_categorized "$PKG/pacman-explicit.txt" "${native[@]}"
write_categorized "$PKG/blackarch.txt"       "${blackarch[@]:-}"
write_categorized "$PKG/aur.txt"             "${foreign[@]:-}"

say "Capturing full package list (reference/verify only — NOT installed)…"
pacman -Qq  > "$PKG/pacman-all.txt"
pacman -Qqe > "$PKG/pacman-explicit-flat.txt"

# ---------------------------------------------------------------------------
# 2. Language-level globals — captured, install lines stay COMMENTED in installer
# ---------------------------------------------------------------------------
say "Capturing language-level global tools (reference)…"
{ npm ls -g --depth=0 2>/dev/null | tail -n +2 || true; } > "$PKG/npm-global.txt"
{ cargo install --list 2>/dev/null | grep -v '^ ' || true; } > "$PKG/cargo.txt"
{ ls "$HOME/go/bin" 2>/dev/null || true; } > "$PKG/go-bin.txt"
{ uv tool list 2>/dev/null || true; } > "$PKG/uv-tools.txt"

# ---------------------------------------------------------------------------
# 3. Dotfiles (curated) — secrets excluded by path, then verified by grep
# ---------------------------------------------------------------------------
say "Capturing curated dotfiles…"
DOTS=(
  .zshrc .zprofile .bashrc .bash_profile .gitconfig
  .config/git .config/nvim .config/ghostty .config/rofi
  .config/wofi .config/fish .config/gh .config/Code/User
)
# gh stores an oauth token in hosts.yml — copy config but drop that file.
GH_DENY=("hosts.yml")

rm -rf "$DOT"; mkdir -p "$DOT"
for rel in "${DOTS[@]}"; do
  src="$HOME/$rel"
  [[ -e "$src" ]] || { warn "skip (absent): $rel"; continue; }
  dst="$DOT/$rel"
  mkdir -p "$(dirname "$dst")"
  if [[ -d "$src" ]]; then
    cp -a "$src" "$(dirname "$dst")/"
  else
    cp -a "$src" "$dst"
  fi
done
# Strip gh credential file if present.
for f in "${GH_DENY[@]}"; do rm -f "$DOT/.config/gh/$f"; done

say "Verifying no secrets leaked into dotfiles…"
if grep -rIlE 'oauth_token|BEGIN [A-Z ]*PRIVATE KEY|api[_-]?key|secret[_-]?key|password[[:space:]]*=[[:space:]]*[^ ]' "$DOT" 2>/dev/null; then
  warn "Potential secret found in captured dotfiles (listed above)."
  warn "Inspect and remove before sharing. Aborting so nothing leaks."
  exit 1
fi

# ---------------------------------------------------------------------------
# 4. GNOME settings via dconf — subtrees only (no monitor IDs / dead paths)
# ---------------------------------------------------------------------------
if command -v dconf >/dev/null; then
  say "Dumping GNOME dconf subtrees…"
  : > "$DCONF/gnome.ini"
  for path in /org/gnome/desktop/ /org/gnome/shell/keybindings/ /org/gnome/settings-daemon/; do
    echo "### DCONF-PATH $path" >> "$DCONF/gnome.ini"
    dconf dump "$path" >> "$DCONF/gnome.ini" 2>/dev/null || true
    echo >> "$DCONF/gnome.ini"
  done
fi

say "Capture complete. Review ./packages, ./dotfiles, ./dconf before committing."
