#!/usr/bin/env bash
# install.sh — reproduce this Arch setup on a NEW machine.
#
# SELF-CONTAINED: the package lists, every dotfile and the GNOME dconf dump are
# embedded in this file. Copy this one file to a new box and run it — no git
# clone, no other files needed.
#
#   ./install.sh              # do it
#   ./install.sh --dry-run    # print every action, change nothing
#
# Run as your normal user (NOT root). Uses sudo per-command; makepkg refuses root.
#
# DO NOT EDIT THIS FILE — it is generated by capture.sh from install-template.sh
# plus the contents of packages/, dotfiles/ and dconf/. Edit the template.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DRY=0
for a in "$@"; do
  case "$a" in
    --dry-run|-n) DRY=1 ;;
    -h|--help)
      cat <<'USAGE'
install.sh — reproduce this Arch setup on a new machine.

  ./install.sh              install everything
  ./install.sh --dry-run    print every action, change nothing
  ./install.sh --help       this text

Self-contained: packages, dotfiles and GNOME settings are embedded in this
file. Run it as your normal user, not root.

Environment:
  ARCH_SETUP_DIR   where embedded files are unpacked
                   (default ~/.local/share/arch-setup)
USAGE
      exit 0 ;;
    *) printf 'unknown argument: %s (try --help)\n' "$a" >&2; exit 1 ;;
  esac
done

say()  { printf '\033[1;34m::\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$*" >&2; }
run()  { if (( DRY )); then printf '\033[2m[dry] %s\033[0m\n' "$*"; else eval "$*"; fi; }

[[ $EUID -eq 0 ]] && { warn "Do not run as root. Run as your user; sudo is used where needed."; exit 1; }
command -v pacman >/dev/null || { warn "Not an Arch system (no pacman)."; exit 1; }

#__PAYLOAD__

# ---------------------------------------------------------------------------
# 0. Where the files live
#
# Running from a repo checkout, use the real directories so the usual
# edit-and-commit workflow still works. Standalone, unpack the embedded copy.
# Dotfiles are SYMLINKED into $HOME, so the unpack target has to be a permanent
# location — a temp dir would leave $HOME full of dangling links.
# ---------------------------------------------------------------------------
UNPACKED=0
if [[ -d "$HERE/packages" && -d "$HERE/dotfiles" && -d "$HERE/dconf" ]]; then
  ROOT="$HERE"
  say "Running from a repo checkout: $ROOT"
elif (( DRY )); then
  ROOT="$(mktemp -d)"
  trap 'rm -rf "$ROOT"' EXIT
  say "Self-contained dry run — unpacking to a temp dir for the preview"
  unpack_payload
else
  ROOT="${ARCH_SETUP_DIR:-$HOME/.local/share/arch-setup}"
  say "Self-contained mode — unpacking embedded files to $ROOT"
  warn "Dotfiles are symlinked out of $ROOT. Keep it; deleting it breaks them."
  unpack_payload
  UNPACKED=1
fi

PKG="$ROOT/packages"
DOT="$ROOT/dotfiles"
DCONF="$ROOT/dconf"
THEME="$ROOT/zsh-theme"

# Read a categorized package file: drop blank lines and #-comments.
read_pkgs() { grep -vE '^\s*#' "$1" 2>/dev/null | grep -vE '^\s*$' || true; }

SKIPPED=()

# Install a package list. One bad package must never kill the whole run --- a
# conflict (repo `code` vs an already-installed AUR `visual-studio-code-bin`) or
# a dropped package aborts the entire pacman transaction. So: try the fast bulk
# install, and if it fails, retry one at a time and report what fell out.
pac_install() {
  local cmd="${PKG_INSTALL_CMD:-sudo pacman -S --needed --noconfirm}"
  local label="$1"; shift
  local pkgs=("$@") failed=() p
  (( ${#pkgs[@]} )) || return 0
  say "Installing ${#pkgs[@]} $label..."
  if run "$cmd ${pkgs[*]}"; then
    return 0
  fi
  warn "Bulk install of $label failed (conflict or unavailable package)."
  warn "Retrying one at a time so the rest still get installed..."
  for p in "${pkgs[@]}"; do
    run "$cmd '$p'" || failed+=("$p")
  done
  if (( ${#failed[@]} )); then
    warn "Skipped ${#failed[@]} $label: ${failed[*]}"
    SKIPPED+=("${failed[@]}")
  fi
}

# ---------------------------------------------------------------------------
# 1. Native pacman packages
# ---------------------------------------------------------------------------
say "Updating package databases…"
run "sudo pacman -Syu --noconfirm"

mapfile -t NATIVE < <(read_pkgs "$PKG/pacman-explicit.txt")
pac_install "native packages" ${NATIVE[@]+"${NATIVE[@]}"}

# ---------------------------------------------------------------------------
# 2. yay (AUR helper) — bootstrap, since yay can't install itself
# ---------------------------------------------------------------------------
if ! command -v yay >/dev/null; then
  say "Bootstrapping yay from AUR…"
  run "sudo pacman -S --needed --noconfirm base-devel git"
  run "tmp=\$(mktemp -d) && git clone https://aur.archlinux.org/yay-bin.git \"\$tmp/yay-bin\" && (cd \"\$tmp/yay-bin\" && makepkg -si --noconfirm)"
fi

# Curated extras the captured configs depend on (Nerd Font, ripgrep, fd,
# fnm-bin...). Installed here rather than with the native packages because some
# are AUR-only; yay handles repo packages transparently, so one pass covers both.
EXTRA_CMD="sudo pacman -S --needed --noconfirm"
if command -v yay >/dev/null; then
  EXTRA_CMD="yay -S --needed --noconfirm"
else
  warn "yay unavailable; installing extras with pacman (AUR entries will be skipped)."
fi
mapfile -t EXTRAS < <(read_pkgs "$PKG/extras.txt")
PKG_INSTALL_CMD="$EXTRA_CMD" \
  pac_install "curated extras (config dependencies)" ${EXTRAS[@]+"${EXTRAS[@]}"}

# ---------------------------------------------------------------------------
# 3. BlackArch repo + its packages (only if we captured any)
# ---------------------------------------------------------------------------
mapfile -t BA < <(read_pkgs "$PKG/blackarch.txt")
if (( ${#BA[@]} )); then
  if ! pacman -Sl blackarch >/dev/null 2>&1; then
    say "Adding BlackArch repository (strap.sh)…"
    warn "This downloads blackarch.org/strap.sh and runs it as root."
    warn "Ctrl-C now if you would rather review it first."
    run "tmp=\$(mktemp -d) && curl -fsSL https://blackarch.org/strap.sh -o \"\$tmp/strap.sh\" && chmod +x \"\$tmp/strap.sh\" && sudo \"\$tmp/strap.sh\""
    run "sudo pacman -Syu --noconfirm"
  fi
  pac_install "BlackArch packages" "${BA[@]}"
fi

# ---------------------------------------------------------------------------
# 4. AUR / foreign packages (best-effort — some captured ones are local builds)
# ---------------------------------------------------------------------------
mapfile -t AUR < <(read_pkgs "$PKG/aur.txt")
if (( ${#AUR[@]} )); then
  say "Installing AUR packages (best-effort)…"
  for p in "${AUR[@]}"; do
    run "yay -S --needed --noconfirm '$p' || echo \"  skip: $p (no AUR PKGBUILD / local build)\""
  done
fi

# ---------------------------------------------------------------------------
# 5. oh-my-zsh (reinstalled from upstream, not copied)
# ---------------------------------------------------------------------------
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  say "Installing oh-my-zsh…"
  run "RUNZSH=no CHSH=no sh -c \"\$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
fi

# Custom zsh plugins referenced by .zshrc's plugins=() line. oh-my-zsh ships
# none of these and there is no repo package for zsh-completions, so a missing
# one makes zsh warn on every shell start. Clone them into $ZSH_CUSTOM.
ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
declare -A ZSH_PLUGINS=(
  [zsh-autosuggestions]="https://github.com/zsh-users/zsh-autosuggestions"
  [zsh-syntax-highlighting]="https://github.com/zsh-users/zsh-syntax-highlighting"
  [zsh-completions]="https://github.com/zsh-users/zsh-completions"
)
for name in "${!ZSH_PLUGINS[@]}"; do
  dest="$ZSH_CUSTOM/plugins/$name"
  if [[ ! -d "$dest" ]]; then
    say "Cloning zsh plugin: $name"
    run "git clone --depth=1 ${ZSH_PLUGINS[$name]} \"$dest\""
  fi
done

# ---------------------------------------------------------------------------
# 5b. zeroday zsh theme (theme file, colour-bitmap font, artwork + helpers).
#     COPIED, not symlinked like the dotfiles: fontconfig only scans real
#     directories, and `zeroday-build` rewrites the artwork in place when the
#     theme is re-skinned. Neither works through a link into a repo checkout.
# ---------------------------------------------------------------------------
if [[ -d "$THEME" ]]; then
  say "Installing zeroday zsh theme…"
  run "mkdir -p \"$ZSH_CUSTOM/themes\" \"$HOME/.local/share/fonts\" \"$HOME/.local/share/zeroday\" \"$HOME/.local/bin\""
  run "cp -a \"$THEME/zeroday.zsh-theme\" \"$ZSH_CUSTOM/themes/\""
  if [[ -f "$THEME/fonts/ZeroDayGlyphs.ttf" ]]; then
    run "cp -a \"$THEME/fonts/ZeroDayGlyphs.ttf\" \"$HOME/.local/share/fonts/\""
    # Skip this and the prompt face renders as two empty boxes.
    run "fc-cache -f \"$HOME/.local/share/fonts\" >/dev/null"
  fi
  if [[ -d "$THEME/zeroday" ]]; then
    run "cp -a \"$THEME/zeroday/.\" \"$HOME/.local/share/zeroday/\""
    run "ln -sfn \"$HOME/.local/share/zeroday/build.sh\" \"$HOME/.local/bin/zeroday-build\""
  fi
fi

# ---------------------------------------------------------------------------
# 6. Dotfiles — symlink into $HOME, backing up anything real that's in the way
# ---------------------------------------------------------------------------
STAMP="$(date +%s)"
BACKUP="$HOME/.pre-setup-backup-$STAMP"
link_one() {
  local src="$1" tgt="$2"
  if [[ -L "$tgt" && "$(readlink -f "$tgt")" == "$(readlink -f "$src")" ]]; then
    return  # already correct
  fi
  if [[ -e "$tgt" || -L "$tgt" ]]; then
    run "mkdir -p \"$BACKUP/\$(dirname '${tgt#$HOME/}')\""
    run "mv \"$tgt\" \"$BACKUP/${tgt#$HOME/}\""
  fi
  run "mkdir -p \"\$(dirname '$tgt')\""
  run "ln -s \"$src\" \"$tgt\""
}

if [[ -d "$DOT" ]]; then
  say "Linking dotfiles (backups -> $BACKUP)…"
  # Link each top-level entry and each item inside .config individually, so we
  # never blow away the whole ~/.config directory.
  while IFS= read -r -d '' f; do
    rel="${f#$DOT/}"
    link_one "$f" "$HOME/$rel"
  done < <(find "$DOT" -mindepth 1 -maxdepth 1 ! -name .config -print0)
  if [[ -d "$DOT/.config" ]]; then
    while IFS= read -r -d '' f; do
      name="$(basename "$f")"
      # VS Code owns .config/Code and writes cache/state there; link only the
      # User/ subdir so its runtime junk never lands in the repo.
      if [[ "$name" == "Code" && -d "$f/User" ]]; then
        link_one "$f/User" "$HOME/.config/Code/User"
      else
        link_one "$f" "$HOME/.config/$name"
      fi
    done < <(find "$DOT/.config" -mindepth 1 -maxdepth 1 -print0)
  fi
fi

# ---------------------------------------------------------------------------
# 7. GNOME dconf restore
# ---------------------------------------------------------------------------
if [[ -f "$DCONF/gnome.ini" ]] && command -v dconf >/dev/null; then
  say "Restoring GNOME dconf settings…"
  path=""; buf=""
  flush() {
    [[ -n "$path" && -n "$buf" ]] || return 0
    if (( DRY )); then
      printf '\033[2m[dry] dconf load %s\033[0m\n' "$path"
    elif ! printf '%s' "$buf" | dconf load "$path"; then
      warn "dconf load failed for $path (continuing)"
    fi
  }
  while IFS= read -r line; do
    if [[ "$line" == "### DCONF-PATH "* ]]; then
      flush; path="${line#'### DCONF-PATH '}"; buf=""
    else
      buf+="$line"$'\n'
    fi
  done < "$DCONF/gnome.ini"
  flush
fi

# ---------------------------------------------------------------------------
# 8. Enable the services this box relies on
# ---------------------------------------------------------------------------
say "Enabling common services (best-effort)…"
for svc in gdm NetworkManager docker cronie; do
  run "sudo systemctl enable $svc.service 2>/dev/null || true"
done

# ---------------------------------------------------------------------------
# 9. Manual follow-ups
# ---------------------------------------------------------------------------
if (( ${#SKIPPED[@]} )); then
  warn "These packages could not be installed and need a manual decision:"
  for p in "${SKIPPED[@]}"; do warn "    $p"; done
fi

cat <<EOF

============================================================
 DONE. Manual steps the script deliberately did NOT do:
============================================================
  - Secrets & keys (excluded on purpose):
      ~/.ssh, ~/.gnupg, ~/.aws         -> copy from a secure backup
      gh auth:  run  \`gh auth login\`
      git:      credential helper is gh; no token stored
  - Language globals (captured, not installed). Review then run:
      $PKG/npm-global.txt, cargo.txt, go-bin.txt, uv-tools.txt
  - Change your login shell to zsh:   chsh -s /usr/bin/zsh
  - Docker group (log out/in after):  sudo usermod -aG docker "\$USER"
  - Reboot to pick up GNOME/dconf and services.
  - zsh theme "zeroday": fully restart the terminal (not just a new tab) so it
    rescans fonts. Two empty boxes in the prompt = the font was not found.
      zeroday                    banner
      zeroday-sticker [rows]     the real artwork (Ghostty/kitty)
      zeroday-build <img> [rows] [crop]   re-skin from any image
EOF

if (( UNPACKED )); then
  cat <<EOF
 ---
 Embedded files were unpacked to: $ROOT
 Your dotfiles are symlinks into that directory — keep it.
EOF
fi

echo "============================================================"
