#!/usr/bin/env bash
# install.sh — reproduce this Arch setup on a NEW machine.
#
# SELF-CONTAINED: the package lists, every dotfile and the GNOME dconf dump are
# embedded in this file. Copy this one file to a new box and run it — no git
# clone, no other files needed.
#
#   ./install.sh              # do it
#   ./install.sh --dry-run    # print every action, change nothing
#
# Run as your normal user (NOT root). Uses sudo per-command; makepkg refuses root.
#
# DO NOT EDIT THIS FILE — it is generated by capture.sh from install-template.sh
# plus the contents of packages/, dotfiles/ and dconf/. Edit the template.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DRY=0
for a in "$@"; do
  case "$a" in
    --dry-run|-n) DRY=1 ;;
    -h|--help)
      cat <<'USAGE'
install.sh — reproduce this Arch setup on a new machine.

  ./install.sh              install everything
  ./install.sh --dry-run    print every action, change nothing
  ./install.sh --help       this text

Self-contained: packages, dotfiles and GNOME settings are embedded in this
file. Run it as your normal user, not root.

Environment:
  ARCH_SETUP_DIR   where embedded files are unpacked
                   (default ~/.local/share/arch-setup)
USAGE
      exit 0 ;;
    *) printf 'unknown argument: %s (try --help)\n' "$a" >&2; exit 1 ;;
  esac
done

say()  { printf '\033[1;34m::\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$*" >&2; }
run()  { if (( DRY )); then printf '\033[2m[dry] %s\033[0m\n' "$*"; else eval "$*"; fi; }

[[ $EUID -eq 0 ]] && { warn "Do not run as root. Run as your user; sudo is used where needed."; exit 1; }
command -v pacman >/dev/null || { warn "Not an Arch system (no pacman)."; exit 1; }

# --- BEGIN EMBEDDED PAYLOAD — generated by capture.sh, do not edit ---
_dir() { mkdir -p "$ROOT/$1"; }
# _file <relpath> <strip-trailing-newline>  — content arrives on stdin.
# A heredoc always ends in a newline; files captured without one are trimmed
# back so the unpacked copy is byte-identical to the original.
_file() {
  local rel="$1" strip="${2:-0}"
  mkdir -p "$ROOT/$(dirname "$rel")"
  cat > "$ROOT/$rel"
  if (( strip )); then truncate -s -1 "$ROOT/$rel"; fi
  return 0
}
unpack_payload() {
  _dir dotfiles/.config/Code/User/snippets
  _file dconf/gnome.ini 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
### DCONF-PATH /org/gnome/desktop/
[app-folders]
folder-children=['System', 'Utilities', 'YaST', 'Pardus']

[app-folders/folders/Pardus]
categories=['X-Pardus-Apps']
name='X-Pardus-Apps.directory'
translate=true

[app-folders/folders/System]
apps=['org.gnome.baobab.desktop', 'org.gnome.DiskUtility.desktop', 'org.gnome.Logs.desktop', 'org.freedesktop.MalcontentControl.desktop', 'org.gnome.SystemMonitor.desktop', 'org.gnome.tweaks.desktop']
name='X-GNOME-Shell-System.directory'
translate=true

[app-folders/folders/Utilities]
apps=['org.gnome.Decibels.desktop', 'org.gnome.Connections.desktop', 'org.gnome.Papers.desktop', 'org.gnome.font-viewer.desktop', 'org.gnome.Loupe.desktop']
name='X-GNOME-Shell-Utilities.directory'
translate=true

[app-folders/folders/YaST]
categories=['X-SuSE-YaST']
name='suse-yast.directory'
translate=true

[background]
picture-options='zoom'
picture-uri='file:///home/yoge/.config/background'
picture-uri-dark='file:///home/yoge/.config/background'
primary-color='#02023c3c8888'

[input-sources]
sources=[('xkb', 'us')]
xkb-options=['terminate:ctrl_alt_bksp']

[interface]
color-scheme='prefer-dark'

[notifications]
application-children=['org-gnome-console', 'gnome-power-panel', 'gnome-about-panel', 'firefox', 'com-mitchellh-ghostty', 'org-gnome-epiphany', 'org-gnome-settings', 'org-gnome-software', 'org-gnome-nautilus']

[notifications/application/com-mitchellh-ghostty]
application-id='com.mitchellh.ghostty.desktop'

[notifications/application/firefox]
application-id='firefox.desktop'

[notifications/application/gnome-about-panel]
application-id='gnome-about-panel.desktop'

[notifications/application/gnome-power-panel]
application-id='gnome-power-panel.desktop'

[notifications/application/org-gnome-console]
application-id='org.gnome.Console.desktop'

[notifications/application/org-gnome-epiphany]
application-id='org.gnome.Epiphany.desktop'

[notifications/application/org-gnome-nautilus]
application-id='org.gnome.Nautilus.desktop'

[notifications/application/org-gnome-settings]
application-id='org.gnome.Settings.desktop'

[notifications/application/org-gnome-software]
application-id='org.gnome.Software.desktop'

[peripherals/keyboard]
numlock-state=true

[session]
idle-delay=uint32 0

[wm/keybindings]
close=['<Super>q']

### DCONF-PATH /org/gnome/shell/keybindings/
[/]
screenshot=['<Control><Alt>s']
show-screenshot-ui=['<Shift><Control>s']

### DCONF-PATH /org/gnome/settings-daemon/
[plugins/color]
night-light-enabled=false
night-light-schedule-automatic=false

[plugins/housekeeping]
donation-reminder-last-shown=int64 1784101818281516

[plugins/media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']
home=['<Super>e']
reboot=['<Shift><Super>r']
shutdown=@as []
volume-down=['<Control>Down']
volume-up=['<Control>Up']

[plugins/media-keys/custom-keybindings/custom0]
binding='<Super>f'
command='firefox'
name='firefox'

[plugins/media-keys/custom-keybindings/custom1]
binding='<Super>Return'
command='ghostty'
name='ghostty'

[plugins/media-keys/custom-keybindings/custom2]
binding='<Shift><Super>v'
command='/home/yoge/.local/bin/copyninja pick'
name='Clipboard History'

[plugins/media-keys/custom-keybindings/custom3]
binding='<Shift><Super>p'
command='poweroff'
name='poweroff'

[plugins/media-keys/custom-keybindings/custom4]
binding='<Shift><Super>t'
command='restart'
name='restart'

[plugins/power]
idle-dim=false
power-button-action='interactive'
sleep-inactive-ac-type='nothing'
sleep-inactive-battery-type='nothing'

__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.bash_profile 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.bashrc 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/Code/User/settings.json 1 <<'__ARCH_SETUP_PAYLOAD_EOF__'
{
    "claudeCode.preferredLocation": "panel"
}
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/gh/config.yml 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
# The current version of the config schema
version: 1
# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# Preference for editor-based interactive prompting. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prefer_editor_prompt: disabled
# A pager program to send command output to, e.g. "less". If blank, will refer to environment. Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
# The path to a unix socket through which to send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
# Whether to display labels using their RGB hex color codes in terminals that support truecolor. Supported values: enabled, disabled
color_labels: disabled
# Whether customizable, 4-bit accessible colors should be used. Supported values: enabled, disabled
accessible_colors: disabled
# Whether an accessible prompter should be used. Supported values: enabled, disabled
accessible_prompter: disabled
# Whether to use an animated spinner as a progress indicator. If disabled, a textual progress indicator is used instead. Supported values: enabled, disabled
spinner: enabled
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/ghostty/config 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
# By default Reload config with shft + cmd + , 

config-file = themes/rosepine
background = #000000
background-opacity = 9.0
background-blur-radius = 20

font-family = JetBrainsMonoNL Nerd Font 
font-size = 14
cursor-style = block
cursor-style-blink = false
cursor-invert-fg-bg = true

mouse-hide-while-typing = true

window-decoration = true
window-padding-x = 10
window-padding-y = 10
window-height = 24
window-padding-balance = true

auto-update = check
auto-update-channel = stable

# extras
shell-integration-features = no-cursor 
copy-on-select = clipboard

# Custom Keybinds & Config (super represents cmd key on mac)
# For Simple Keybinds
# keybind = super+r=reload_config 
keybind = super+i=inspector:toggle
keybind = super+b>,=toggle_quick_terminal

# Similar Tmux but with Ghostty
# (ctrl b for tmux -> cmb b for ghostty)
keybind = super+b>r=reload_config
keybind = super+b>x=close_surface
# this only works if you have `macos-titlebar-style = tabs or native or transparent`
# else it behaves like new window
keybind = super+b>c=new_tab 
keybind = super+b>n=new_window

# tab nav
keybind = super+b>1=goto_tab:1
keybind = super+b>2=goto_tab:2
keybind = super+b>3=goto_tab:3
keybind = super+b>4=goto_tab:4
keybind = super+b>5=goto_tab:5
keybind = super+b>6=goto_tab:6
keybind = super+b>7=goto_tab:7
keybind = super+b>8=goto_tab:8
keybind = super+b>9=goto_tab:9

# splitting
keybind = super+b>\=new_split:right
keybind = super+b>-=new_split:down
keybind = super+b>e=equalize_splits

# split nav (setting this to control will not work if tmux already uses it)
keybind = super+b>h=goto_split:left
keybind = super+b>j=goto_split:bottom
keybind = super+b>k=goto_split:top
keybind = super+b>l=goto_split:right

#Shaders
# custom-shader = shaders/bettercrt.glsl
# custom-shader = shaders/retro-terminal.glsl
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/ghostty/themes/rosepine 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
background = #000000
foreground = #e0def4
selection-foreground = #e0def4
selection-background = #2a2837
palette = 0=#26233a
palette = 1=#eb6f92
palette = 2=#9ccfd8
palette = 3=#f6c177
palette = 4=#31748f
palette = 5=#c4a7e7
palette = 6=#ebbcba
palette = 7=#e0def4
palette = 8=#6e6a86
palette = 9=#eb6f92
palette = 10=#9ccfd8
palette = 11=#f6c177
palette = 12=#31748f
palette = 13=#c4a7e7
palette = 14=#ebbcba
palette = 15=#e0def4
palette = 16=#000000
palette = 17=#00005f
palette = 18=#000087
palette = 19=#0000af
palette = 20=#0000d7
palette = 21=#0000ff
palette = 22=#005f00
palette = 23=#005f5f
palette = 24=#005f87
palette = 25=#005faf
palette = 26=#005fd7
palette = 27=#005fff
palette = 28=#008700
palette = 29=#00875f
palette = 30=#008787
palette = 31=#0087af
palette = 32=#0087d7
palette = 33=#0087ff
palette = 34=#00af00
palette = 35=#00af5f
palette = 36=#00af87
palette = 37=#00afaf
palette = 38=#00afd7
palette = 39=#00afff
palette = 40=#00d700
palette = 41=#00d75f
palette = 42=#00d787
palette = 43=#00d7af
palette = 44=#00d7d7
palette = 45=#00d7ff
palette = 46=#00ff00
palette = 47=#00ff5f
palette = 48=#00ff87
palette = 49=#00ffaf
palette = 50=#00ffd7
palette = 51=#00ffff
palette = 52=#5f0000
palette = 53=#5f005f
palette = 54=#5f0087
palette = 55=#5f00af
palette = 56=#5f00d7
palette = 57=#5f00ff
palette = 58=#5f5f00
palette = 59=#5f5f5f
palette = 60=#5f5f87
palette = 61=#5f5faf
palette = 62=#5f5fd7
palette = 63=#5f5fff
palette = 64=#5f8700
palette = 65=#5f875f
palette = 66=#5f8787
palette = 67=#5f87af
palette = 68=#5f87d7
palette = 69=#5f87ff
palette = 70=#5faf00
palette = 71=#5faf5f
palette = 72=#5faf87
palette = 73=#5fafaf
palette = 74=#5fafd7
palette = 75=#5fafff
palette = 76=#5fd700
palette = 77=#5fd75f
palette = 78=#5fd787
palette = 79=#5fd7af
palette = 80=#5fd7d7
palette = 81=#5fd7ff
palette = 82=#5fff00
palette = 83=#5fff5f
palette = 84=#5fff87
palette = 85=#5fffaf
palette = 86=#5fffd7
palette = 87=#5fffff
palette = 88=#870000
palette = 89=#87005f
palette = 90=#870087
palette = 91=#8700af
palette = 92=#8700d7
palette = 93=#8700ff
palette = 94=#875f00
palette = 95=#875f5f
palette = 96=#875f87
palette = 97=#875faf
palette = 98=#875fd7
palette = 99=#875fff
palette = 100=#878700
palette = 101=#87875f
palette = 102=#878787
palette = 103=#8787af
palette = 104=#8787d7
palette = 105=#8787ff
palette = 106=#87af00
palette = 107=#87af5f
palette = 108=#87af87
palette = 109=#87afaf
palette = 110=#87afd7
palette = 111=#87afff
palette = 112=#87d700
palette = 113=#87d75f
palette = 114=#87d787
palette = 115=#87d7af
palette = 116=#87d7d7
palette = 117=#87d7ff
palette = 118=#87ff00
palette = 119=#87ff5f
palette = 120=#87ff87
palette = 121=#87ffaf
palette = 122=#87ffd7
palette = 123=#87ffff
palette = 124=#af0000
palette = 125=#af005f
palette = 126=#af0087
palette = 127=#af00af
palette = 128=#af00d7
palette = 129=#af00ff
palette = 130=#af5f00
palette = 131=#af5f5f
palette = 132=#af5f87
palette = 133=#af5faf
palette = 134=#af5fd7
palette = 135=#af5fff
palette = 136=#af8700
palette = 137=#af875f
palette = 138=#af8787
palette = 139=#af87af
palette = 140=#af87d7
palette = 141=#af87ff
palette = 142=#afaf00
palette = 143=#afaf5f
palette = 144=#afaf87
palette = 145=#afafaf
palette = 146=#afafd7
palette = 147=#afafff
palette = 148=#afd700
palette = 149=#afd75f
palette = 150=#afd787
palette = 151=#afd7af
palette = 152=#afd7d7
palette = 153=#afd7ff
palette = 154=#afff00
palette = 155=#afff5f
palette = 156=#afff87
palette = 157=#afffaf
palette = 158=#afffd7
palette = 159=#afffff
palette = 160=#d70000
palette = 161=#d7005f
palette = 162=#d70087
palette = 163=#d700af
palette = 164=#d700d7
palette = 165=#d700ff
palette = 166=#d75f00
palette = 167=#d75f5f
palette = 168=#d75f87
palette = 169=#d75faf
palette = 170=#d75fd7
palette = 171=#d75fff
palette = 172=#d78700
palette = 173=#d7875f
palette = 174=#d78787
palette = 175=#d787af
palette = 176=#d787d7
palette = 177=#d787ff
palette = 178=#d7af00
palette = 179=#d7af5f
palette = 180=#d7af87
palette = 181=#d7afaf
palette = 182=#d7afd7
palette = 183=#d7afff
palette = 184=#d7d700
palette = 185=#d7d75f
palette = 186=#d7d787
palette = 187=#d7d7af
palette = 188=#d7d7d7
palette = 189=#d7d7ff
palette = 190=#d7ff00
palette = 191=#d7ff5f
palette = 192=#d7ff87
palette = 193=#d7ffaf
palette = 194=#d7ffd7
palette = 195=#d7ffff
palette = 196=#ff0000
palette = 197=#ff005f
palette = 198=#ff0087
palette = 199=#ff00af
palette = 200=#ff00d7
palette = 201=#ff00ff
palette = 202=#ff5f00
palette = 203=#ff5f5f
palette = 204=#ff5f87
palette = 205=#ff5faf
palette = 206=#ff5fd7
palette = 207=#ff5fff
palette = 208=#ff8700
palette = 209=#ff875f
palette = 210=#ff8787
palette = 211=#ff87af
palette = 212=#ff87d7
palette = 213=#ff87ff
palette = 214=#ffaf00
palette = 215=#ffaf5f
palette = 216=#ffaf87
palette = 217=#ffafaf
palette = 218=#ffafd7
palette = 219=#ffafff
palette = 220=#ffd700
palette = 221=#ffd75f
palette = 222=#ffd787
palette = 223=#ffd7af
palette = 224=#ffd7d7
palette = 225=#ffd7ff
palette = 226=#ffff00
palette = 227=#ffff5f
palette = 228=#ffff87
palette = 229=#ffffaf
palette = 230=#ffffd7
palette = 231=#ffffff
palette = 232=#080808
palette = 233=#121212
palette = 234=#1c1c1c
palette = 235=#262626
palette = 236=#303030
palette = 237=#3a3a3a
palette = 238=#444444
palette = 239=#4e4e4e
palette = 240=#585858
palette = 241=#626262
palette = 242=#6c6c6c
palette = 243=#767676
palette = 244=#808080
palette = 245=#8a8a8a
palette = 246=#949494
palette = 247=#9e9e9e
palette = 248=#a8a8a8
palette = 249=#b2b2b2
palette = 250=#bcbcbc
palette = 251=#c6c6c6
palette = 252=#d0d0d0
palette = 253=#dadada
palette = 254=#e4e4e4
palette = 255=#eeeeee
cursor-color = #555169
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/nvim/.gitignore 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
tt.*
.tests
doc/tags
debug
.repro
foo.*
*.log
data
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/nvim/init.lua 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/nvim/lazy-lock.json 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
{
  "LazyVim": { "branch": "main", "commit": "c10948c50b18fae7f256433afdef09e432410480" },
  "blink.cmp": { "branch": "main", "commit": "78336bc89ee5365633bcf754d93df01678b5c08f" },
  "bufferline.nvim": { "branch": "main", "commit": "655133c3b4c3e5e05ec549b9f8cc2894ac6f51b3" },
  "catppuccin": { "branch": "main", "commit": "05e8787020dcfdb937bf2ff23855ea2415b4e072" },
  "conform.nvim": { "branch": "master", "commit": "619363c30309d29ffa631e67c8183f2a72caa373" },
  "flash.nvim": { "branch": "main", "commit": "b6346946d10d07998efee029fb0f7a593806d0cd" },
  "friendly-snippets": { "branch": "main", "commit": "6cd7280adead7f586db6fccbd15d2cac7e2188b9" },
  "gitsigns.nvim": { "branch": "main", "commit": "31d6fb2d618bca1482b9f274751ead5f03461408" },
  "grug-far.nvim": { "branch": "main", "commit": "1cc080f55706b38aabfa97d40acb6adf59ac4a5a" },
  "lazy.nvim": { "branch": "main", "commit": "85c7ff3711b730b4030d03144f6db6375044ae82" },
  "lazydev.nvim": { "branch": "main", "commit": "ff2cbcba459b637ec3fd165a2be59b7bbaeedf0d" },
  "lualine.nvim": { "branch": "master", "commit": "221ce6b2d999187044529f49da6554a92f740a96" },
  "mason-lspconfig.nvim": { "branch": "main", "commit": "a4068c3ebd4cb335b25239e5ea35c22ee6007962" },
  "mason.nvim": { "branch": "main", "commit": "2a6940af80375532e5e9e7c1f2fc6319a1b7a69d" },
  "mini.ai": { "branch": "main", "commit": "25248c6aa002391936a6200f12d1466015987133" },
  "mini.icons": { "branch": "main", "commit": "98faae31e9be1cc054ae63485e58ceb185efcad0" },
  "mini.pairs": { "branch": "main", "commit": "b1fd9df3bb4a41c8f45778a3859ee80ef6b367e3" },
  "noice.nvim": { "branch": "main", "commit": "7bfd942445fb63089b59f97ca487d605e715f155" },
  "nui.nvim": { "branch": "main", "commit": "de740991c12411b663994b2860f1a4fd0937c130" },
  "nvim-lint": { "branch": "master", "commit": "a219b2c9e5b4765e5c845aba119dad55806fcaf1" },
  "nvim-lspconfig": { "branch": "master", "commit": "d592c1e6ad9a0a01b3d5ed3f0345d68407167181" },
  "nvim-treesitter": { "branch": "main", "commit": "bd41519ff7901da11ba6e1c8f419f17f2d94305a" },
  "nvim-treesitter-textobjects": { "branch": "main", "commit": "898ee307df58f854d11cd7edd06472574d48014e" },
  "nvim-ts-autotag": { "branch": "main", "commit": "88c1453db4ba7dd24131086fe51fdf74e587d275" },
  "persistence.nvim": { "branch": "main", "commit": "b20b2a7887bd39c1a356980b45e03250f3dce49c" },
  "plenary.nvim": { "branch": "master", "commit": "74b06c6c75e4eeb3108ec01852001636d85a932b" },
  "snacks.nvim": { "branch": "main", "commit": "882c996cf28183f4d63640de0b4c02ec886d01f2" },
  "todo-comments.nvim": { "branch": "main", "commit": "31e3c38ce9b29781e4422fc0322eb0a21f4e8668" },
  "tokyonight.nvim": { "branch": "main", "commit": "cdc07ac78467a233fd62c493de29a17e0cf2b2b6" },
  "trouble.nvim": { "branch": "main", "commit": "bd67efe408d4816e25e8491cc5ad4088e708a69a" },
  "ts-comments.nvim": { "branch": "main", "commit": "a59d6092213447450191122c9346f309161504cb" },
  "which-key.nvim": { "branch": "main", "commit": "3aab2147e74890957785941f0c1ad87d0a44c15a" }
}
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/nvim/lazyvim.json 1 <<'__ARCH_SETUP_PAYLOAD_EOF__'
{
  "extras": [

  ],
  "install_version": 8,
  "news": {
    "NEWS.md": "11866"
  },
  "version": 8
}
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/nvim/LICENSE 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.

      "Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.

      "Legal Entity" shall mean the union of the acting entity and all
      other entities that control, are controlled by, or are under common
      control with that entity. For the purposes of this definition,
      "control" means (i) the power, direct or indirect, to cause the
      direction or management of such entity, whether by contract or
      otherwise, or (ii) ownership of fifty percent (50%) or more of the
      outstanding shares, or (iii) beneficial ownership of such entity.

      "You" (or "Your") shall mean an individual or Legal Entity
      exercising permissions granted by this License.

      "Source" form shall mean the preferred form for making modifications,
      including but not limited to software source code, documentation
      source, and configuration files.

      "Object" form shall mean any form resulting from mechanical
      transformation or translation of a Source form, including but
      not limited to compiled object code, generated documentation,
      and conversions to other media types.

      "Work" shall mean the work of authorship, whether in Source or
      Object form, made available under the License, as indicated by a
      copyright notice that is included in or attached to the work
      (an example is provided in the Appendix below).

      "Derivative Works" shall mean any work, whether in Source or Object
      form, that is based on (or derived from) the Work and for which the
      editorial revisions, annotations, elaborations, or other modifications
      represent, as a whole, an original work of authorship. For the purposes
      of this License, Derivative Works shall not include works that remain
      separable from, or merely link (or bind by name) to the interfaces of,
      the Work and Derivative Works thereof.

      "Contribution" shall mean any work of authorship, including
      the original version of the Work and any modifications or additions
      to that Work or Derivative Works thereof, that is intentionally
      submitted to Licensor for inclusion in the Work by the copyright owner
      or by an individual or Legal Entity authorized to submit on behalf of
      the copyright owner. For the purposes of this definition, "submitted"
      means any form of electronic, verbal, or written communication sent
      to the Licensor or its representatives, including but not limited to
      communication on electronic mailing lists, source code control systems,
      and issue tracking systems that are managed by, or on behalf of, the
      Licensor for the purpose of discussing and improving the Work, but
      excluding communication that is conspicuously marked or otherwise
      designated in writing by the copyright owner as "Not a Contribution."

      "Contributor" shall mean Licensor and any individual or Legal Entity
      on behalf of whom a Contribution has been received by Licensor and
      subsequently incorporated within the Work.

   2. Grant of Copyright License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      copyright license to reproduce, prepare Derivative Works of,
      publicly display, publicly perform, sublicense, and distribute the
      Work and such Derivative Works in Source or Object form.

   3. Grant of Patent License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      (except as stated in this section) patent license to make, have made,
      use, offer to sell, sell, import, and otherwise transfer the Work,
      where such license applies only to those patent claims licensable
      by such Contributor that are necessarily infringed by their
      Contribution(s) alone or by combination of their Contribution(s)
      with the Work to which such Contribution(s) was submitted. If You
      institute patent litigation against any entity (including a
      cross-claim or counterclaim in a lawsuit) alleging that the Work
      or a Contribution incorporated within the Work constitutes direct
      or contributory patent infringement, then any patent licenses
      granted to You under this License for that Work shall terminate
      as of the date such litigation is filed.

   4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and

      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and

      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works; and

      (d) If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.

      You may add Your own copyright statement to Your modifications and
      may provide additional or different license terms and conditions
      for use, reproduction, or distribution of Your modifications, or
      for any such Derivative Works as a whole, provided Your use,
      reproduction, and distribution of the Work otherwise complies with
      the conditions stated in this License.

   5. Submission of Contributions. Unless You explicitly state otherwise,
      any Contribution intentionally submitted for inclusion in the Work
      by You to the Licensor shall be under the terms and conditions of
      this License, without any additional terms or conditions.
      Notwithstanding the above, nothing herein shall supersede or modify
      the terms of any separate license agreement you may have executed
      with Licensor regarding such Contributions.

   6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.

   7. Disclaimer of Warranty. Unless required by applicable law or
      agreed to in writing, Licensor provides the Work (and each
      Contributor provides its Contributions) on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
      implied, including, without limitation, any warranties or conditions
      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
      PARTICULAR PURPOSE. You are solely responsible for determining the
      appropriateness of using or redistributing the Work and assume any
      risks associated with Your exercise of permissions under this License.

   8. Limitation of Liability. In no event and under no legal theory,
      whether in tort (including negligence), contract, or otherwise,
      unless required by applicable law (such as deliberate and grossly
      negligent acts) or agreed to in writing, shall any Contributor be
      liable to You for damages, including any direct, indirect, special,
      incidental, or consequential damages of any character arising as a
      result of this License or out of the use or inability to use the
      Work (including but not limited to damages for loss of goodwill,
      work stoppage, computer failure or malfunction, or any and all
      other commercial damages or losses), even if such Contributor
      has been advised of the possibility of such damages.

   9. Accepting Warranty or Additional Liability. While redistributing
      the Work or Derivative Works thereof, You may choose to offer,
      and charge a fee for, acceptance of support, warranty, indemnity,
      or other liability obligations and/or rights consistent with this
      License. However, in accepting such obligations, You may act only
      on Your own behalf and on Your sole responsibility, not on behalf
      of any other Contributor, and only if You agree to indemnify,
      defend, and hold each Contributor harmless for any liability
      incurred by, or claims asserted against, such Contributor by reason
      of your accepting any such warranty or additional liability.

   END OF TERMS AND CONDITIONS

   APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

   Copyright [yyyy] [name of copyright owner]

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/nvim/lua/config/autocmds.lua 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/nvim/lua/config/keymaps.lua 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/nvim/lua/config/lazy.lua 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out, "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import/override with your plugins
    { import = "plugins" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  install = { colorscheme = { "tokyonight", "habamax" } },
  checker = {
    enabled = true, -- check for plugin updates periodically
    notify = false, -- notify on update
  }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/nvim/lua/config/options.lua 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/nvim/lua/plugins/example.lua 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
-- since this is just an example spec, don't actually load anything here and return an empty spec
-- stylua: ignore
if true then return {} end

-- every spec file under the "plugins" directory will be loaded automatically by lazy.nvim
--
-- In your plugin files, you can:
-- * add extra plugins
-- * disable/enabled LazyVim plugins
-- * override the configuration of LazyVim plugins
return {
  -- add gruvbox
  { "ellisonleao/gruvbox.nvim" },

  -- Configure LazyVim to load gruvbox
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "gruvbox",
    },
  },

  -- change trouble config
  {
    "folke/trouble.nvim",
    -- opts will be merged with the parent spec
    opts = { use_diagnostic_signs = true },
  },

  -- disable trouble
  { "folke/trouble.nvim", enabled = false },

  -- override nvim-cmp and add cmp-emoji
  {
    "hrsh7th/nvim-cmp",
    dependencies = { "hrsh7th/cmp-emoji" },
    ---@param opts cmp.ConfigSchema
    opts = function(_, opts)
      table.insert(opts.sources, { name = "emoji" })
    end,
  },

  -- change some telescope options and a keymap to browse plugin files
  {
    "nvim-telescope/telescope.nvim",
    keys = {
      -- add a keymap to browse plugin files
      -- stylua: ignore
      {
        "<leader>fp",
        function() require("telescope.builtin").find_files({ cwd = require("lazy.core.config").options.root }) end,
        desc = "Find Plugin File",
      },
    },
    -- change some options
    opts = {
      defaults = {
        layout_strategy = "horizontal",
        layout_config = { prompt_position = "top" },
        sorting_strategy = "ascending",
        winblend = 0,
      },
    },
  },

  -- add pyright to lspconfig
  {
    "neovim/nvim-lspconfig",
    ---@class PluginLspOpts
    opts = {
      ---@type lspconfig.options
      servers = {
        -- pyright will be automatically installed with mason and loaded with lspconfig
        pyright = {},
      },
    },
  },

  -- add tsserver and setup with typescript.nvim instead of lspconfig
  {
    "neovim/nvim-lspconfig",
    dependencies = {
      "jose-elias-alvarez/typescript.nvim",
      init = function()
        require("lazyvim.util").lsp.on_attach(function(_, buffer)
          -- stylua: ignore
          vim.keymap.set( "n", "<leader>co", "TypescriptOrganizeImports", { buffer = buffer, desc = "Organize Imports" })
          vim.keymap.set("n", "<leader>cR", "TypescriptRenameFile", { desc = "Rename File", buffer = buffer })
        end)
      end,
    },
    ---@class PluginLspOpts
    opts = {
      ---@type lspconfig.options
      servers = {
        -- tsserver will be automatically installed with mason and loaded with lspconfig
        tsserver = {},
      },
      -- you can do any additional lsp server setup here
      -- return true if you don't want this server to be setup with lspconfig
      ---@type table<string, fun(server:string, opts:_.lspconfig.options):boolean?>
      setup = {
        -- example to setup with typescript.nvim
        tsserver = function(_, opts)
          require("typescript").setup({ server = opts })
          return true
        end,
        -- Specify * to use this function as a fallback for any server
        -- ["*"] = function(server, opts) end,
      },
    },
  },

  -- for typescript, LazyVim also includes extra specs to properly setup lspconfig,
  -- treesitter, mason and typescript.nvim. So instead of the above, you can use:
  { import = "lazyvim.plugins.extras.lang.typescript" },

  -- add more treesitter parsers
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "tsx",
        "typescript",
        "vim",
        "yaml",
      },
    },
  },

  -- since `vim.tbl_deep_extend`, can only merge tables and not lists, the code above
  -- would overwrite `ensure_installed` with the new value.
  -- If you'd rather extend the default config, use the code below instead:
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      -- add tsx and treesitter
      vim.list_extend(opts.ensure_installed, {
        "tsx",
        "typescript",
      })
    end,
  },

  -- the opts function can also be used to change the default opts:
  {
    "nvim-lualine/lualine.nvim",
    event = "VeryLazy",
    opts = function(_, opts)
      table.insert(opts.sections.lualine_x, {
        function()
          return "😄"
        end,
      })
    end,
  },

  -- or you can return new options to override all the defaults
  {
    "nvim-lualine/lualine.nvim",
    event = "VeryLazy",
    opts = function()
      return {
        --[[add your custom lualine config here]]
      }
    end,
  },

  -- use mini.starter instead of alpha
  { import = "lazyvim.plugins.extras.ui.mini-starter" },

  -- add jsonls and schemastore packages, and setup treesitter for json, json5 and jsonc
  { import = "lazyvim.plugins.extras.lang.json" },

  -- add any tools you want to have installed below
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "stylua",
        "shellcheck",
        "shfmt",
        "flake8",
      },
    },
  },
}
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/nvim/.neoconf.json 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
{
  "neodev": {
    "library": {
      "enabled": true,
      "plugins": true
    }
  },
  "neoconf": {
    "plugins": {
      "lua_ls": {
        "enabled": true
      }
    }
  }
}
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/nvim/README.md 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
# 💤 LazyVim

A starter template for [LazyVim](https://github.com/LazyVim/LazyVim).
Refer to the [documentation](https://lazyvim.github.io/installation) to get started.
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.config/nvim/stylua.toml 1 <<'__ARCH_SETUP_PAYLOAD_EOF__'
indent_type = "Spaces"
indent_width = 2
column_width = 120
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.gitconfig 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
[credential "https://github.com"]
	helper = 
	helper = !/usr/bin/gh auth git-credential
[credential "https://gist.github.com"]
	helper = 
	helper = !/usr/bin/gh auth git-credential
__ARCH_SETUP_PAYLOAD_EOF__
  _file dotfiles/.zshrc 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="cloud"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-syntax-highlighting zsh-completions)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# fnm (Node version manager). The upstream installer drops it in
# ~/.local/share/fnm; the fnm-bin package puts it in /usr/bin. Support both,
# and stay quiet if neither is present.
FNM_PATH="$HOME/.local/share/fnm"
[ -d "$FNM_PATH" ] && export PATH="$FNM_PATH:$PATH"
if command -v fnm >/dev/null; then
  eval "$(fnm env --shell zsh)"
fi

# CLI aliases
alias ls="eza --icons"
alias ll="eza -la --icons --git"
alias la="eza -a --icons"
alias cat="bat"
alias grep="rg"
alias find="fd"
alias top="btop"

# VPN & Tor toggles — all disabled by default
tor-on()   { sudo systemctl start tor && echo "[Tor] Started"; }
tor-off()  { sudo systemctl stop tor  && echo "[Tor] Stopped"; }
tor-check() { torsocks curl -s https://check.torproject.org/api/ip; }

# OpenVPN helper — pass your .ovpn file path as argument
vpn-on()   { [[ -n "$1" ]] && sudo openvpn --config "$1" || echo "Usage: vpn-on /path/to/config.ovpn"; }

# WireGuard helpers — pass interface name (e.g. wg0)
wg-on()    { [[ -n "$1" ]] && sudo wg-quick up "$1"   || echo "Usage: wg-on <interface>"; }
wg-off()   { [[ -n "$1" ]] && sudo wg-quick down "$1" || echo "Usage: wg-off <interface>"; }
wg-status() { sudo wg show; }

# sshd toggles — masked when off, so nothing can pull it back up implicitly
ssh-on()     { sudo systemctl unmask sshd && sudo systemctl enable --now sshd && echo "[sshd] Enabled and running"; }
ssh-off()    { sudo systemctl stop sshd && sudo systemctl disable sshd && sudo systemctl mask sshd && echo "[sshd] Stopped, disabled and masked"; }
export PATH="$HOME/.local/bin:$PATH"
__ARCH_SETUP_PAYLOAD_EOF__
  _file packages/aur.txt 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
# Generated by capture.sh on 2026-09-03T17:20:21+05:30
# Lines starting with # are comments; installer ignores them.

## Dev-Tools
visual-studio-code-bin

__ARCH_SETUP_PAYLOAD_EOF__
  _file packages/blackarch.txt 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
# Generated by capture.sh on 2026-09-03T17:20:21+05:30
# Lines starting with # are comments; installer ignores them.

## Security-Web
burpsuite

## System-Base
blackarch-mirrorlist

__ARCH_SETUP_PAYLOAD_EOF__
  _file packages/cargo.txt 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
__ARCH_SETUP_PAYLOAD_EOF__
  _file packages/extras.txt 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
# Curated extras — packages the CAPTURED CONFIGS need but that weren't
# installed on the source machine, so `capture.sh` couldn't pick them up.
# Maintained by hand; capture.sh never overwrites this file.
# Installed by install.sh via yay, after the AUR helper is bootstrapped ---
# some entries (fnm-bin) are AUR-only and pacman cannot install them.

## Fonts (Ghostty config requests JetBrainsMono Nerd Font)
ttf-jetbrains-mono-nerd

## Neovim / LazyVim runtime deps (Telescope live-grep, file finding, :checkhealth)
ripgrep
fd

## Node toolchain (.zshrc initialises fnm; installed to ~/.local/share/fnm by
## the upstream script, so capture.sh can never see it as a package)
fnm-bin
__ARCH_SETUP_PAYLOAD_EOF__
  _file packages/go-bin.txt 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
gopls
__ARCH_SETUP_PAYLOAD_EOF__
  _file packages/npm-global.txt 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
├── @anthropic-ai/claude-code@2.1.218
├── node-gyp@13.0.2
├── nopt@10.0.1
├── npm@12.0.2
└── semver@7.8.5

__ARCH_SETUP_PAYLOAD_EOF__
  _file packages/pacman-all.txt 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
7zip
aalib
abseil-cpp
accountsservice
acl
ada
adwaita-cursors
adwaita-fonts
adwaita-icon-theme
adwaita-icon-theme-legacy
afpfs-ng
aircrack-ng
alsa-card-profiles
alsa-lib
alsa-topology-conf
alsa-ucm-conf
alsa-utils
aom
apache
appstream
apr
apr-util
archlinux-keyring
arp-scan
at-spi2-core
attr
audit
autoconf
automake
avahi
baobab
base
base-devel
bash
bat
bcg729
bind
binutils
binwalk
bison
blackarch-mirrorlist
bluez
bluez-libs
bluez-obex
bluez-utils
bolt
boost-libs
brltty
brotli
btop
bubblewrap
burpsuite
bzip2
c-ares
ca-certificates
ca-certificates-mozilla
ca-certificates-utils
cairo
cairomm-1.16
capstone
cdparanoia
cfitsio
chromaprint
cifs-utils
clang
cmake
colord
colord-gtk-common
colord-gtk4
colord-sane
compiler-rt
composefs
containerd
coreutils
cpio
cppdap
cracklib
cryptsetup
cups-pk-helper
curl
dav1d
db5.3
dbus
dbus-broker
dbus-broker-units
dbus-units
dconf
debugedit
debuginfod
decibels
default-cursors
desktop-file-utils
device-mapper
diffutils
djvulibre
dnsmasq
dnssec-anchors
docker
docker-compose
dotconf
double-conversion
dtc
duktape
e2fsprogs
editorconfig-core-c
edk2-aarch64
edk2-ovmf
edk2-riscv64
efibootmgr
efivar
egl-wayland
eglexternalplatform
electron39
electron43
elfutils
ell
enchant
epiphany
espeak-ng
ethtool
evince
evolution-data-server
exempi
exiv2
expat
exploitdb
eza
faac
faad2
fakeroot
fd
ffmpeg
fftw
file
filesystem
findutils
firefox
flac
flatpak
flex
fluidsynth
folks
fontconfig
freeglut
freerdp
freetype2
fribidi
fuse-common
fuse2
fuse3
fzf
gawk
gc
gcc
gcc-libs
gcr
gcr-4
gd
gdb
gdb-common
gdbm
gdk-pixbuf2
gdm
geoclue
geocode-glib
gettext
gexiv2
gexiv2-common
gfxstream
ghidra
ghostscript
ghostty
ghostty-shell-integration
ghostty-terminfo
giflib
git
github-cli
gjs
glib-networking
glib2
glibc
glibmm-2.68
glm
glslang
glu
glusterfs
glycin
glycin-gtk4
gmp
gnome-app-list
gnome-autoar
gnome-backgrounds
gnome-bluetooth-3.0
gnome-calculator
gnome-calendar
gnome-characters
gnome-clocks
gnome-color-manager
gnome-connections
gnome-console
gnome-contacts
gnome-control-center
gnome-desktop
gnome-desktop-4
gnome-desktop-common
gnome-disk-utility
gnome-font-viewer
gnome-keybindings
gnome-keyring
gnome-logs
gnome-maps
gnome-menus
gnome-music
gnome-online-accounts
gnome-remote-desktop
gnome-session
gnome-settings-daemon
gnome-shell
gnome-software
gnome-system-monitor
gnome-text-editor
gnome-tour
gnome-tweaks
gnome-user-docs
gnome-user-share
gnome-weather
gnu-free-fonts
gnulib-l10n
gnupg
gnutls
go
gobject-introspection-runtime
gobuster
gom
gperftools
gpgme
gpgmepp
gpm
graphene
graphite
grep
grilo
grilo-plugins
groff
gsettings-desktop-schemas
gsettings-system-schemas
gsfonts
gsm
gsound
gspell
gssdp
gst-devtools-libs
gst-editing-services
gst-plugin-gtk
gst-plugin-gtk4
gst-plugin-pipewire
gst-plugins-bad
gst-plugins-bad-libs
gst-plugins-base
gst-plugins-base-libs
gst-plugins-good
gst-python
gst-thumbnailers
gstreamer
gtest
gtk-update-icon-cache
gtk-vnc
gtk3
gtk4
gtk4-layer-shell
gtkmm-4.0
gtksourceview4
gtksourceview5
guile
gupnp
gupnp-av
gupnp-dlna
gupnp-igd
gvfs
gvfs-afc
gvfs-dnssd
gvfs-goa
gvfs-gphoto2
gvfs-mtp
gvfs-nfs
gvfs-onedrive
gvfs-smb
gvfs-wsdd
gweather-locations
gzip
harfbuzz
harfbuzz-icu
hashcat
hdf5
hicolor-icon-theme
hidapi
highway
htop
httpie
hwdata
hwloc
hydra
hyphen
iana-etc
ibus
icu
iio-sensor-proxy
ijs
imagemagick
imath
imlib2
inetutils
iniparser
intel-gmmlib
intel-media-driver
intel-ucode
ipcalc
iproute2
iptables
iputils
iso-codes
iw
iwd
jansson
java-environment-common
java-runtime-common
jbig2dec
jbigkit
jdk-openjdk
jemalloc
john
jq
js140
json-c
json-glib
jsoncpp
kbd
keyutils
kmod
krb5
l-smash
lame
lazygit
lcms2
ldb
leancrypto
libadwaita
libaec
libaemu
libaio
libao
libarchive
libasan
libass
libassuan
libasyncns
libatasmart
libatomic
libavc1394
libavif
libavtp
libb2
libblake3
libblockdev
libblockdev-crypto
libblockdev-fs
libblockdev-loop
libblockdev-mdraid
libblockdev-nvme
libblockdev-part
libblockdev-smart
libblockdev-swap
libbluray
libbpf
libbs2b
libbsd
libburn
libbytesize
libcaca
libcacard
libcanberra
libcap
libcap-ng
libcbor
libcdio
libcdio-paranoia
libcgif
libcloudproviders
libcolord
libcue
libcups
libdaemon
libdatrie
libdbusmenu-glib
libdbusmenu-gtk3
libdc1394
libdca
libde265
libdecor
libdeflate
libdisplay-info
libdmapsharing
libdovi
libdrm
libdv
libdvdnav
libdvdread
libebur128
libedataserverui4
libedit
libei
libelf
libepoxy
libevdev
libevent
libexif
libfabric
libfbclient
libfdk-aac
libffi
libfido2
libfontenc
libfreeaptx
libfyaml
libgcc
libgcrypt
libgdm
libgee
libgfortran
libgirepository
libgit2
libglvnd
libgme
libgoa
libgomp
libgpg-error
libgphoto2
libgsf
libgsystemservice
libgtop
libgudev
libgusb
libgweather-4
libgxps
libhandy
libheif
libhwasan
libibus
libical
libice
libidn
libidn2
libiec61883
libieee1284
libimagequant
libimobiledevice
libimobiledevice-glue
libinih
libinput
libiptcdata
libiscsi
libisl
libisoburn
libisofs
libjpeg-turbo
libjxl
libksba
liblc3
libldac
libldap
liblouis
liblqr
liblrdf
liblsan
libltc
libluv
libmakepkg-dropins
libmalcontent
libmanette
libmatio
libmaxminddb
libmbim
libmd
libmediaart
libmemcached-awesome
libmicrodns
libmicrohttpd
libmm-glib
libmnl
libmodplug
libmpc
libmpcdec
libmtp
libmysofa
libnautilus-extension
libnbd
libndp
libnet
libnetfilter_conntrack
libnewt
libnfnetlink
libnfs
libnftnl
libnghttp2
libnghttp3
libngtcp2
libnice
libnl
libnm
libnma-common
libnma-gtk4
libnotify
libnsl
libnvme
liboauth
libobjc
libogg
libopenmpt
libosinfo
libp11-kit
libpaper
libpathrs
libpcap
libpciaccess
libpgm
libphonenumber
libpipewire
libplacebo
libplist
libpng
libportal
libportal-gtk4
libproxy
libpsl
libpulse
libpwquality
libqmi
libqrtr-glib
libquadmath
libraqm
libraw
libraw1394
librest
librsvg
libsamplerate
libsasl
libseccomp
libsecret
libshout
libshumate
libsigc++-3.0
libslirp
libsm
libsndfile
libsodium
libsonic
libsoup3
libsoxr
libspectre
libspeechd
libspelling
libsrtp
libssc
libssh
libssh2
libstdc++
libstemmer
libsynctex
libsysprof-capture
libtasn1
libtatsu
libteam
libthai
libtheora
libtiff
libtirpc
libtommath
libtool
libtraceevent
libtracefs
libtsan
libubsan
libunibreak
libunistring
libunwind
liburcu
liburing
libusb
libusbmuxd
libutf8proc
libuv
libva
libva-intel-driver
libvdpau
libverto
libvips
libvirt
libvirt-glib
libvirt-python
libvncserver
libvorbis
libvpl
libvpx
libvterm
libwacom
libwbclient
libwebp
libwireplumber
libwnck3
libx11
libxau
libxaw
libxcb
libxcomposite
libxcrypt
libxcursor
libxcvt
libxdamage
libxdmcp
libxdp
libxext
libxfixes
libxfont2
libxft
libxi
libxinerama
libxkbcommon
libxkbcommon-x11
libxkbfile
libxml2
libxmlb
libxmu
libxpm
libxrandr
libxrender
libxres
libxshmfence
libxslt
libxss
libxt
libxtst
libxv
libxxf86vm
libyaml
libyuv
libzip
licenses
lilv
linux
linux-api-headers
linux-firmware
linux-firmware-amdgpu
linux-firmware-atheros
linux-firmware-broadcom
linux-firmware-cirrus
linux-firmware-intel
linux-firmware-mediatek
linux-firmware-nvidia
linux-firmware-other
linux-firmware-radeon
linux-firmware-realtek
linux-firmware-whence
llhttp
llvm-libs
lm_sensors
lmdb
localsearch
loupe
lsof
ltrace
lua
lua51-lpeg
lua54
luajit
lv2
lz4
lzo
m4
mailcap
make
malcontent
mariadb-libs
masscan
md4c
mdadm
mesa
metasploit
minizip
mjpegtools
mkinitcpio
mkinitcpio-busybox
mobile-broadband-provider-info
mod_dnssd
mongo-c-driver
mpdecimal
mpfr
mpg123
msgpack-c
msgraph
mtdev
mtr
multipath-tools
mutter
nano
nautilus
ncurses
ndctl
neon
neovim
net-snmp
net-tools
nettle
networkmanager
nftables
nikto
nmap
node-gyp
nodejs
nodejs-nopt
noto-fonts-emoji
npm
npth
nspr
nss
numactl
obsidian
ocl-icd
onetbb
oniguruma
openai-codex
openal
openbsd-netcat
opencore-amr
openexr
openh264
openjpeg2
openjph
openmpi
openpmix
openssh
openssl
openucx
openvpn
opus
orc
orca
osinfo-db
ostree
p11-kit
pacman
pacman-mirrorlist
pam
pambase
pango
pangomm-2.48
papers
parted
patch
pcaudiolib
pciutils
pcre
pcre2
pcsclite
perl
perl-clone
perl-encode-locale
perl-error
perl-file-listing
perl-html-parser
perl-html-tagset
perl-http-cookiejar
perl-http-cookies
perl-http-daemon
perl-http-date
perl-http-message
perl-http-negotiate
perl-io-html
perl-json
perl-libwww
perl-lwp-mediatypes
perl-mailtools
perl-mime-base32
perl-net-http
perl-net-ssleay
perl-timedate
perl-try-tiny
perl-uri
perl-www-robotrules
phodav
pinentry
pipewire
pipewire-alsa
pipewire-audio
pipewire-jack
pipewire-pulse
pixman
pkcs11-helper
pkgconf
polkit
poppler
poppler-data
poppler-glib
popt
portaudio
postgresql-libs
procps-ng
protobuf
protobuf-c
proxychains-ng
prrte
psmisc
python
python-argcomplete
python-attrs
python-brltty
python-cairo
python-certifi
python-cffi
python-charset-normalizer
python-click
python-cryptography
python-dasbus
python-dbus
python-defusedxml
python-distro
python-filelock
python-gobject
python-idna
python-markdown-it-py
python-mdurl
python-multidict
python-packaging
python-pip
python-pipx
python-platformdirs
python-psutil
python-pycparser
python-pygments
python-pysocks
python-pyxdg
python-requests
python-requests-toolbelt
python-rich
python-setproctitle
python-systemd
python-tomlkit
python-typing_extensions
python-urllib3
python-userpath
python-wheel
python-xmltodict
python-yaml
qemu-audio-alsa
qemu-audio-dbus
qemu-audio-jack
qemu-audio-oss
qemu-audio-pa
qemu-audio-pipewire
qemu-audio-sdl
qemu-audio-spice
qemu-base
qemu-block-curl
qemu-block-dmg
qemu-block-iscsi
qemu-block-nfs
qemu-block-ssh
qemu-chardev-baum
qemu-chardev-spice
qemu-common
qemu-desktop
qemu-docs
qemu-emulators-full
qemu-full
qemu-hw-display-qxl
qemu-hw-display-virtio-gpu
qemu-hw-display-virtio-gpu-gl
qemu-hw-display-virtio-gpu-pci
qemu-hw-display-virtio-gpu-pci-gl
qemu-hw-display-virtio-gpu-pci-rutabaga
qemu-hw-display-virtio-gpu-rutabaga
qemu-hw-display-virtio-vga
qemu-hw-display-virtio-vga-gl
qemu-hw-display-virtio-vga-rutabaga
qemu-hw-s390x-virtio-gpu-ccw
qemu-hw-uefi-vars
qemu-hw-usb-host
qemu-hw-usb-redirect
qemu-hw-usb-smartcard
qemu-img
qemu-pr-helper
qemu-system-aarch64
qemu-system-alpha
qemu-system-alpha-firmware
qemu-system-arm
qemu-system-arm-firmware
qemu-system-avr
qemu-system-hexagon
qemu-system-hppa
qemu-system-hppa-firmware
qemu-system-loongarch64
qemu-system-m68k
qemu-system-microblaze
qemu-system-microblaze-firmware
qemu-system-mips
qemu-system-or1k
qemu-system-ppc
qemu-system-ppc-firmware
qemu-system-riscv
qemu-system-riscv-firmware
qemu-system-rx
qemu-system-s390x
qemu-system-s390x-firmware
qemu-system-sh4
qemu-system-sparc
qemu-system-sparc-firmware
qemu-system-tricore
qemu-system-x86
qemu-system-x86-firmware
qemu-system-xtensa
qemu-tests
qemu-tools
qemu-ui-curses
qemu-ui-dbus
qemu-ui-egl-headless
qemu-ui-gtk
qemu-ui-opengl
qemu-ui-sdl
qemu-ui-spice-app
qemu-ui-spice-core
qemu-user
qemu-vhost-user-gpu
qemu-vmsr-helper
qrencode
qt6-5compat
qt6-base
qt6-declarative
qt6-multimedia
qt6-multimedia-ffmpeg
qt6-shadertools
qt6-svg
qt6-translations
radare2
raptor
rav1e
rdma-core
readline
rhash
ripgrep
rpcbind
rtmpdump
rubberband
ruby
ruby-bundler
ruby-erb
rubygems
runc
rutabaga-ffi
rygel
sane
sbc
sdl2-compat
sdl2_image
sdl3
sdl3_ttf
seabios
sed
semver
serd
serf
shaderc
shadow
shared-mime-info
showtime
simdjson
simple-scan
slang
smartmontools
smbclient
snappy
snapshot
sndio
sord
sound-theme-freedesktop
soundtouch
source-highlight
spandsp
speech-dispatcher
speex
speexdsp
spice
spice-gtk
spice-protocol
spirv-tools
sqlite
sqlmap
sratom
srt
startup-notification
strace
subversion
sudo
sushi
svt-av1
svt-hevc
systemd
systemd-libs
systemd-sysvcompat
taglib
talloc
tar
tcpdump
tdb
tealdeer
tecla
tevent
texinfo
tinysparql
tor
torsocks
totem-pl-parser
tpm2-tss
tree-sitter
tree-sitter-c
tree-sitter-lua
tree-sitter-markdown
tree-sitter-query
tree-sitter-vim
tree-sitter-vimdoc
tslib
twolame
tzdata
uchardet
udisks2
ufw
unibilium
unzip
upower
usbmuxd
usbredir
usbutils
util-linux
util-linux-libs
v4l-utils
vapoursynth
vde2
vid.stab
vim
vim-runtime
virglrenderer
virt-install
virt-manager
virtiofsd
visual-studio-code-bin
vmaf
volume_key
vte-common
vte3
vte4
vulkan-icd-loader
vulkan-intel
vulkan-mesa-implicit-layers
vulkan-nouveau
vulkan-radeon
vulkan-tools
wavpack
wayland
webkit2gtk-4.1
webkitgtk-6.0
webrtc-audio-processing-1
wget
which
whois
wildmidi
wireguard-tools
wireless_tools
wireplumber
wireshark-cli
wireshark-qt
wl-clipboard
woff2
wolfssl
wpa_supplicant
wsdd
wtype
x264
x265
xcb-proto
xcb-util
xcb-util-cursor
xcb-util-image
xcb-util-keysyms
xcb-util-renderutil
xcb-util-wm
xclip
xdg-dbus-proxy
xdg-desktop-portal
xdg-desktop-portal-gnome
xdg-desktop-portal-gtk
xdg-user-dirs
xdg-user-dirs-gtk
xdg-utils
xdotool
xf86-video-amdgpu
xf86-video-ati
xf86-video-nouveau
xkeyboard-config
xorg-fonts-encodings
xorg-server-common
xorg-setxkbmap
xorg-xkbcomp
xorg-xmodmap
xorg-xprop
xorg-xwayland
xorgproto
xvidcore
xxhash
xz
yay
yay-debug
ydotool
yelp
yelp-xsl
yq
zbar
zed
zeromq
zimg
zint
zip
zix
zlib
zlib-ng
zram-generator
zsh
zsh-autosuggestions
zsh-syntax-highlighting
zstd
zvbi
zxing-cpp
__ARCH_SETUP_PAYLOAD_EOF__
  _file packages/pacman-explicit-flat.txt 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
7zip
aircrack-ng
alsa-utils
arp-scan
baobab
base
base-devel
bat
bind
binwalk
blackarch-mirrorlist
bluez
bluez-utils
btop
burpsuite
clang
cmake
debuginfod
decibels
dnsmasq
docker
docker-compose
efibootmgr
epiphany
exploitdb
eza
fd
firefox
fzf
gcc
gdm
ghidra
ghostty
git
github-cli
gnome-backgrounds
gnome-calculator
gnome-calendar
gnome-characters
gnome-clocks
gnome-color-manager
gnome-connections
gnome-console
gnome-contacts
gnome-control-center
gnome-disk-utility
gnome-font-viewer
gnome-keyring
gnome-logs
gnome-maps
gnome-menus
gnome-music
gnome-remote-desktop
gnome-session
gnome-settings-daemon
gnome-shell
gnome-software
gnome-system-monitor
gnome-text-editor
gnome-tour
gnome-tweaks
gnome-user-docs
gnome-user-share
gnome-weather
gobuster
grilo-plugins
gst-plugin-pipewire
gst-thumbnailers
gvfs
gvfs-afc
gvfs-dnssd
gvfs-goa
gvfs-gphoto2
gvfs-mtp
gvfs-nfs
gvfs-onedrive
gvfs-smb
gvfs-wsdd
hashcat
htop
httpie
hydra
intel-media-driver
intel-ucode
ipcalc
iwd
john
jq
lazygit
libpulse
libva-intel-driver
libvirt
linux
linux-firmware
loupe
ltrace
make
malcontent
masscan
metasploit
mtr
nano
nautilus
neovim
networkmanager
nikto
nmap
obsidian
openai-codex
openssh
openvpn
orca
papers
pipewire
pipewire-alsa
pipewire-jack
pipewire-pulse
proxychains-ng
python-pip
python-pipx
qemu-full
radare2
ripgrep
rygel
showtime
simple-scan
smartmontools
snapshot
sqlmap
strace
sudo
sushi
tcpdump
tealdeer
tecla
tor
torsocks
ufw
vim
virt-manager
visual-studio-code-bin
vulkan-intel
vulkan-nouveau
vulkan-radeon
wget
whois
wireguard-tools
wireplumber
wireshark-qt
wl-clipboard
wtype
xclip
xdg-desktop-portal-gnome
xdg-user-dirs-gtk
xdg-utils
xdotool
xf86-video-amdgpu
xf86-video-ati
xf86-video-nouveau
ydotool
yelp
yq
zed
zip
zram-generator
zsh
zsh-autosuggestions
zsh-syntax-highlighting
__ARCH_SETUP_PAYLOAD_EOF__
  _file packages/pacman-explicit.txt 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
# Generated by capture.sh on 2026-09-03T17:20:21+05:30
# Lines starting with # are comments; installer ignores them.

## Apps
epiphany
firefox
obsidian
openai-codex

## Dev-Tools
clang
cmake
debuginfod
docker
docker-compose
gcc
libvirt
make
python-pip
python-pipx
qemu-full
virt-manager
zed

## GNOME-Desktop
baobab
decibels
gdm
gnome-backgrounds
gnome-calculator
gnome-calendar
gnome-characters
gnome-clocks
gnome-color-manager
gnome-connections
gnome-console
gnome-contacts
gnome-control-center
gnome-disk-utility
gnome-font-viewer
gnome-keyring
gnome-logs
gnome-maps
gnome-menus
gnome-music
gnome-remote-desktop
gnome-session
gnome-settings-daemon
gnome-shell
gnome-software
gnome-system-monitor
gnome-text-editor
gnome-tour
gnome-tweaks
gnome-user-docs
gnome-user-share
gnome-weather
grilo-plugins
gst-plugin-pipewire
gst-thumbnailers
loupe
malcontent
nautilus
orca
papers
rygel
showtime
simple-scan
snapshot
sushi
tecla
xdg-desktop-portal-gnome
xdg-user-dirs-gtk
xdg-utils
yelp

## Security-Anon
proxychains-ng
tor
torsocks

## Security-Cracking
hashcat
hydra
john

## Security-Exploit
exploitdb
metasploit

## Security-Forensics
binwalk
ghidra
ltrace
radare2
strace
wireshark-qt

## Security-Recon
arp-scan
bind
ipcalc
masscan
mtr
nmap
tcpdump
whois

## Security-Web
gobuster
nikto
sqlmap

## Security-Wireless
aircrack-ng

## System-Base
alsa-utils
base
base-devel
bluez
bluez-utils
dnsmasq
efibootmgr
gvfs
gvfs-afc
gvfs-dnssd
gvfs-goa
gvfs-gphoto2
gvfs-mtp
gvfs-nfs
gvfs-onedrive
gvfs-smb
gvfs-wsdd
intel-media-driver
intel-ucode
iwd
libpulse
libva-intel-driver
linux
linux-firmware
networkmanager
openvpn
pipewire
pipewire-alsa
pipewire-jack
pipewire-pulse
sudo
ufw
vulkan-intel
vulkan-nouveau
vulkan-radeon
wireguard-tools
wireplumber
wtype
xdotool
xf86-video-amdgpu
xf86-video-ati
xf86-video-nouveau
ydotool
zram-generator

## Terminal-CLI
7zip
bat
btop
eza
fd
fzf
ghostty
git
github-cli
htop
httpie
jq
lazygit
nano
neovim
openssh
ripgrep
smartmontools
tealdeer
vim
wget
wl-clipboard
xclip
yq
zip
zsh
zsh-autosuggestions
zsh-syntax-highlighting

__ARCH_SETUP_PAYLOAD_EOF__
  _file packages/uv-tools.txt 0 <<'__ARCH_SETUP_PAYLOAD_EOF__'
__ARCH_SETUP_PAYLOAD_EOF__
}
# --- END EMBEDDED PAYLOAD ---

# ---------------------------------------------------------------------------
# 0. Where the files live
#
# Running from a repo checkout, use the real directories so the usual
# edit-and-commit workflow still works. Standalone, unpack the embedded copy.
# Dotfiles are SYMLINKED into $HOME, so the unpack target has to be a permanent
# location — a temp dir would leave $HOME full of dangling links.
# ---------------------------------------------------------------------------
UNPACKED=0
if [[ -d "$HERE/packages" && -d "$HERE/dotfiles" && -d "$HERE/dconf" ]]; then
  ROOT="$HERE"
  say "Running from a repo checkout: $ROOT"
elif (( DRY )); then
  ROOT="$(mktemp -d)"
  trap 'rm -rf "$ROOT"' EXIT
  say "Self-contained dry run — unpacking to a temp dir for the preview"
  unpack_payload
else
  ROOT="${ARCH_SETUP_DIR:-$HOME/.local/share/arch-setup}"
  say "Self-contained mode — unpacking embedded files to $ROOT"
  warn "Dotfiles are symlinked out of $ROOT. Keep it; deleting it breaks them."
  unpack_payload
  UNPACKED=1
fi

PKG="$ROOT/packages"
DOT="$ROOT/dotfiles"
DCONF="$ROOT/dconf"

# Read a categorized package file: drop blank lines and #-comments.
read_pkgs() { grep -vE '^\s*#' "$1" 2>/dev/null | grep -vE '^\s*$' || true; }

SKIPPED=()

# Install a package list. One bad package must never kill the whole run --- a
# conflict (repo `code` vs an already-installed AUR `visual-studio-code-bin`) or
# a dropped package aborts the entire pacman transaction. So: try the fast bulk
# install, and if it fails, retry one at a time and report what fell out.
pac_install() {
  local cmd="${PKG_INSTALL_CMD:-sudo pacman -S --needed --noconfirm}"
  local label="$1"; shift
  local pkgs=("$@") failed=() p
  (( ${#pkgs[@]} )) || return 0
  say "Installing ${#pkgs[@]} $label..."
  if run "$cmd ${pkgs[*]}"; then
    return 0
  fi
  warn "Bulk install of $label failed (conflict or unavailable package)."
  warn "Retrying one at a time so the rest still get installed..."
  for p in "${pkgs[@]}"; do
    run "$cmd '$p'" || failed+=("$p")
  done
  if (( ${#failed[@]} )); then
    warn "Skipped ${#failed[@]} $label: ${failed[*]}"
    SKIPPED+=("${failed[@]}")
  fi
}

# ---------------------------------------------------------------------------
# 1. Native pacman packages
# ---------------------------------------------------------------------------
say "Updating package databases…"
run "sudo pacman -Syu --noconfirm"

mapfile -t NATIVE < <(read_pkgs "$PKG/pacman-explicit.txt")
pac_install "native packages" ${NATIVE[@]+"${NATIVE[@]}"}

# ---------------------------------------------------------------------------
# 2. yay (AUR helper) — bootstrap, since yay can't install itself
# ---------------------------------------------------------------------------
if ! command -v yay >/dev/null; then
  say "Bootstrapping yay from AUR…"
  run "sudo pacman -S --needed --noconfirm base-devel git"
  run "tmp=\$(mktemp -d) && git clone https://aur.archlinux.org/yay-bin.git \"\$tmp/yay-bin\" && (cd \"\$tmp/yay-bin\" && makepkg -si --noconfirm)"
fi

# Curated extras the captured configs depend on (Nerd Font, ripgrep, fd,
# fnm-bin...). Installed here rather than with the native packages because some
# are AUR-only; yay handles repo packages transparently, so one pass covers both.
EXTRA_CMD="sudo pacman -S --needed --noconfirm"
if command -v yay >/dev/null; then
  EXTRA_CMD="yay -S --needed --noconfirm"
else
  warn "yay unavailable; installing extras with pacman (AUR entries will be skipped)."
fi
mapfile -t EXTRAS < <(read_pkgs "$PKG/extras.txt")
PKG_INSTALL_CMD="$EXTRA_CMD" \
  pac_install "curated extras (config dependencies)" ${EXTRAS[@]+"${EXTRAS[@]}"}

# ---------------------------------------------------------------------------
# 3. BlackArch repo + its packages (only if we captured any)
# ---------------------------------------------------------------------------
mapfile -t BA < <(read_pkgs "$PKG/blackarch.txt")
if (( ${#BA[@]} )); then
  if ! pacman -Sl blackarch >/dev/null 2>&1; then
    say "Adding BlackArch repository (strap.sh)…"
    warn "This downloads blackarch.org/strap.sh and runs it as root."
    warn "Ctrl-C now if you would rather review it first."
    run "tmp=\$(mktemp -d) && curl -fsSL https://blackarch.org/strap.sh -o \"\$tmp/strap.sh\" && chmod +x \"\$tmp/strap.sh\" && sudo \"\$tmp/strap.sh\""
    run "sudo pacman -Syu --noconfirm"
  fi
  pac_install "BlackArch packages" "${BA[@]}"
fi

# ---------------------------------------------------------------------------
# 4. AUR / foreign packages (best-effort — some captured ones are local builds)
# ---------------------------------------------------------------------------
mapfile -t AUR < <(read_pkgs "$PKG/aur.txt")
if (( ${#AUR[@]} )); then
  say "Installing AUR packages (best-effort)…"
  for p in "${AUR[@]}"; do
    run "yay -S --needed --noconfirm '$p' || echo \"  skip: $p (no AUR PKGBUILD / local build)\""
  done
fi

# ---------------------------------------------------------------------------
# 5. oh-my-zsh (reinstalled from upstream, not copied)
# ---------------------------------------------------------------------------
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  say "Installing oh-my-zsh…"
  run "RUNZSH=no CHSH=no sh -c \"\$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
fi

# Custom zsh plugins referenced by .zshrc's plugins=() line. oh-my-zsh ships
# none of these and there is no repo package for zsh-completions, so a missing
# one makes zsh warn on every shell start. Clone them into $ZSH_CUSTOM.
ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
declare -A ZSH_PLUGINS=(
  [zsh-autosuggestions]="https://github.com/zsh-users/zsh-autosuggestions"
  [zsh-syntax-highlighting]="https://github.com/zsh-users/zsh-syntax-highlighting"
  [zsh-completions]="https://github.com/zsh-users/zsh-completions"
)
for name in "${!ZSH_PLUGINS[@]}"; do
  dest="$ZSH_CUSTOM/plugins/$name"
  if [[ ! -d "$dest" ]]; then
    say "Cloning zsh plugin: $name"
    run "git clone --depth=1 ${ZSH_PLUGINS[$name]} \"$dest\""
  fi
done

# ---------------------------------------------------------------------------
# 6. Dotfiles — symlink into $HOME, backing up anything real that's in the way
# ---------------------------------------------------------------------------
STAMP="$(date +%s)"
BACKUP="$HOME/.pre-setup-backup-$STAMP"
link_one() {
  local src="$1" tgt="$2"
  if [[ -L "$tgt" && "$(readlink -f "$tgt")" == "$(readlink -f "$src")" ]]; then
    return  # already correct
  fi
  if [[ -e "$tgt" || -L "$tgt" ]]; then
    run "mkdir -p \"$BACKUP/\$(dirname '${tgt#$HOME/}')\""
    run "mv \"$tgt\" \"$BACKUP/${tgt#$HOME/}\""
  fi
  run "mkdir -p \"\$(dirname '$tgt')\""
  run "ln -s \"$src\" \"$tgt\""
}

if [[ -d "$DOT" ]]; then
  say "Linking dotfiles (backups -> $BACKUP)…"
  # Link each top-level entry and each item inside .config individually, so we
  # never blow away the whole ~/.config directory.
  while IFS= read -r -d '' f; do
    rel="${f#$DOT/}"
    link_one "$f" "$HOME/$rel"
  done < <(find "$DOT" -mindepth 1 -maxdepth 1 ! -name .config -print0)
  if [[ -d "$DOT/.config" ]]; then
    while IFS= read -r -d '' f; do
      name="$(basename "$f")"
      # VS Code owns .config/Code and writes cache/state there; link only the
      # User/ subdir so its runtime junk never lands in the repo.
      if [[ "$name" == "Code" && -d "$f/User" ]]; then
        link_one "$f/User" "$HOME/.config/Code/User"
      else
        link_one "$f" "$HOME/.config/$name"
      fi
    done < <(find "$DOT/.config" -mindepth 1 -maxdepth 1 -print0)
  fi
fi

# ---------------------------------------------------------------------------
# 7. GNOME dconf restore
# ---------------------------------------------------------------------------
if [[ -f "$DCONF/gnome.ini" ]] && command -v dconf >/dev/null; then
  say "Restoring GNOME dconf settings…"
  path=""; buf=""
  flush() {
    [[ -n "$path" && -n "$buf" ]] || return 0
    if (( DRY )); then
      printf '\033[2m[dry] dconf load %s\033[0m\n' "$path"
    elif ! printf '%s' "$buf" | dconf load "$path"; then
      warn "dconf load failed for $path (continuing)"
    fi
  }
  while IFS= read -r line; do
    if [[ "$line" == "### DCONF-PATH "* ]]; then
      flush; path="${line#'### DCONF-PATH '}"; buf=""
    else
      buf+="$line"$'\n'
    fi
  done < "$DCONF/gnome.ini"
  flush
fi

# ---------------------------------------------------------------------------
# 8. Enable the services this box relies on
# ---------------------------------------------------------------------------
say "Enabling common services (best-effort)…"
for svc in gdm NetworkManager docker cronie; do
  run "sudo systemctl enable $svc.service 2>/dev/null || true"
done

# ---------------------------------------------------------------------------
# 9. Manual follow-ups
# ---------------------------------------------------------------------------
if (( ${#SKIPPED[@]} )); then
  warn "These packages could not be installed and need a manual decision:"
  for p in "${SKIPPED[@]}"; do warn "    $p"; done
fi

cat <<EOF

============================================================
 DONE. Manual steps the script deliberately did NOT do:
============================================================
  - Secrets & keys (excluded on purpose):
      ~/.ssh, ~/.gnupg, ~/.aws         -> copy from a secure backup
      gh auth:  run  \`gh auth login\`
      git:      credential helper is gh; no token stored
  - Language globals (captured, not installed). Review then run:
      $PKG/npm-global.txt, cargo.txt, go-bin.txt, uv-tools.txt
  - Change your login shell to zsh:   chsh -s /usr/bin/zsh
  - Docker group (log out/in after):  sudo usermod -aG docker "\$USER"
  - Reboot to pick up GNOME/dconf and services.
EOF

if (( UNPACKED )); then
  cat <<EOF
 ---
 Embedded files were unpacked to: $ROOT
 Your dotfiles are symlinks into that directory — keep it.
EOF
fi

echo "============================================================"
