### DCONF-PATH /org/gnome/desktop/
[a11y]
always-show-universal-access-status=false

[app-folders]
folder-children=['System', 'Utilities', 'YaST', 'Pardus']

[app-folders/folders/Pardus]
categories=['X-Pardus-Apps']
name='X-Pardus-Apps.directory'
translate=true

[app-folders/folders/System]
apps=['org.gnome.baobab.desktop', 'org.gnome.DiskUtility.desktop', 'org.gnome.Logs.desktop', 'org.freedesktop.MalcontentControl.desktop', 'org.gnome.SystemMonitor.desktop']
name='X-GNOME-Shell-System.directory'
translate=true

[app-folders/folders/Utilities]
apps=['org.gnome.Decibels.desktop', 'org.gnome.Connections.desktop', 'org.gnome.Papers.desktop', 'org.gnome.font-viewer.desktop', 'org.gnome.Loupe.desktop']
name='X-GNOME-Shell-Utilities.directory'
translate=true

[app-folders/folders/YaST]
categories=['X-SuSE-YaST']
name='suse-yast.directory'
translate=true

[background]
picture-options='zoom'
picture-uri='file:///home/inkyank-03/.config/variety/wallpaper/wallpaper-auto-rotated-f9b84db1a3526f9c69a7cd6c36df1f81.jpg'
picture-uri-dark='file:///home/inkyank-03/.config/variety/wallpaper/wallpaper-auto-rotated-f9b84db1a3526f9c69a7cd6c36df1f81.jpg'
primary-color='#02023c3c8888'

[input-sources]
sources=[('xkb', 'us')]
xkb-options=['terminate:ctrl_alt_bksp', 'lv3:ralt_switch']

[interface]
accent-color='purple'
color-scheme='prefer-dark'
toolkit-accessibility=true

[notifications]
application-children=['firefox', 'gnome-power-panel', 'gnome-about-panel', 'code-oss', 'org-gnome-nautilus', 'com-mitchellh-ghostty', 'org-gnome-console', 'org-gnome-showtime', 'install4j-16tny68-burpsuitecommunity', 'google-chrome', 'claude-desktop', 'libreoffice-writer', 'org-gnome-baobab', 'libreoffice-calc', 'install4j-16tny68-burpsuite']

[notifications/application/claude-desktop]
application-id='claude-desktop.desktop'

[notifications/application/code-oss]
application-id='code-oss.desktop'

[notifications/application/com-mitchellh-ghostty]
application-id='com.mitchellh.ghostty.desktop'

[notifications/application/firefox]
application-id='firefox.desktop'

[notifications/application/gnome-about-panel]
application-id='gnome-about-panel.desktop'

[notifications/application/gnome-power-panel]
application-id='gnome-power-panel.desktop'

[notifications/application/google-chrome]
application-id='google-chrome.desktop'

[notifications/application/install4j-16tny68-burpsuite]
application-id='install4j_16tny68-BurpSuite.desktop'

[notifications/application/install4j-16tny68-burpsuitecommunity]
application-id='install4j_16tny68-BurpSuiteCommunity.desktop'

[notifications/application/libreoffice-calc]
application-id='libreoffice-calc.desktop'

[notifications/application/libreoffice-writer]
application-id='libreoffice-writer.desktop'

[notifications/application/org-gnome-baobab]
application-id='org.gnome.baobab.desktop'

[notifications/application/org-gnome-console]
application-id='org.gnome.Console.desktop'

[notifications/application/org-gnome-nautilus]
application-id='org.gnome.Nautilus.desktop'

[notifications/application/org-gnome-showtime]
application-id='org.gnome.Showtime.desktop'

[peripherals/keyboard]
numlock-state=true

[peripherals/mouse]
speed=-0.40000000000000002

[peripherals/touchpad]
two-finger-scrolling-enabled=true

[screensaver]
picture-uri='file:////usr/share/dynamic-wallpaper/images/aurora/11.jpg'

[search-providers]
sort-order=['org.gnome.Settings.desktop', 'org.gnome.Contacts.desktop', 'org.gnome.Nautilus.desktop']

[session]
idle-delay=uint32 0

[wm/keybindings]
close=['<Super>q']

### DCONF-PATH /org/gnome/shell/keybindings/
[/]
screenshot=['<Control><Alt>s']
screenshot-window=['<Alt>s']
show-screenshot-ui=['<Shift><Control>s']

### DCONF-PATH /org/gnome/settings-daemon/
[plugins/color]
night-light-enabled=false
night-light-schedule-automatic=false

[plugins/housekeeping]
donation-reminder-last-shown=int64 1769764137578910

[plugins/media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/']
home=['<Super>e']

[plugins/media-keys/custom-keybindings/custom0]
binding='<Super>Return'
command='ghostty'
name='ghostty'

[plugins/media-keys/custom-keybindings/custom1]
binding='<Shift><Super>p'
command='poweroff'
name='poweroff'

[plugins/media-keys/custom-keybindings/custom2]
binding='<Super>f'
command='firefox'
name='firefix'

[plugins/media-keys/custom-keybindings/custom3]
binding='<Shift><Super>v'
command='/home/inkyank-03/.local/bin/copyninja pick'
name='Clipboard History'

[plugins/media-keys/custom-keybindings/custom4]
binding='<Shift><Super>r'
command='reboot'
name='reboot'

[plugins/power]
sleep-inactive-ac-type='nothing'

