### DCONF-PATH /org/gnome/desktop/
[app-folders]
folder-children=['System', 'Utilities', 'YaST', 'Pardus']

[app-folders/folders/Pardus]
categories=['X-Pardus-Apps']
name='X-Pardus-Apps.directory'
translate=true

[app-folders/folders/System]
apps=['org.gnome.baobab.desktop', 'org.gnome.DiskUtility.desktop', 'org.gnome.Logs.desktop', 'org.freedesktop.MalcontentControl.desktop', 'org.gnome.SystemMonitor.desktop', 'org.gnome.tweaks.desktop']
name='X-GNOME-Shell-System.directory'
translate=true

[app-folders/folders/Utilities]
apps=['org.gnome.Decibels.desktop', 'org.gnome.Connections.desktop', 'org.gnome.Papers.desktop', 'org.gnome.font-viewer.desktop', 'org.gnome.Loupe.desktop']
name='X-GNOME-Shell-Utilities.directory'
translate=true

[app-folders/folders/YaST]
categories=['X-SuSE-YaST']
name='suse-yast.directory'
translate=true

[background]
picture-options='zoom'
picture-uri='file:///home/yoge/.config/background'
picture-uri-dark='file:///home/yoge/.config/background'
primary-color='#02023c3c8888'

[input-sources]
sources=[('xkb', 'us')]
xkb-options=['terminate:ctrl_alt_bksp']

[interface]
color-scheme='prefer-dark'

[notifications]
application-children=['org-gnome-console', 'gnome-power-panel', 'gnome-about-panel', 'firefox', 'com-mitchellh-ghostty', 'org-gnome-epiphany', 'org-gnome-settings', 'org-gnome-software', 'org-gnome-nautilus']

[notifications/application/com-mitchellh-ghostty]
application-id='com.mitchellh.ghostty.desktop'

[notifications/application/firefox]
application-id='firefox.desktop'

[notifications/application/gnome-about-panel]
application-id='gnome-about-panel.desktop'

[notifications/application/gnome-power-panel]
application-id='gnome-power-panel.desktop'

[notifications/application/org-gnome-console]
application-id='org.gnome.Console.desktop'

[notifications/application/org-gnome-epiphany]
application-id='org.gnome.Epiphany.desktop'

[notifications/application/org-gnome-nautilus]
application-id='org.gnome.Nautilus.desktop'

[notifications/application/org-gnome-settings]
application-id='org.gnome.Settings.desktop'

[notifications/application/org-gnome-software]
application-id='org.gnome.Software.desktop'

[peripherals/keyboard]
numlock-state=true

[session]
idle-delay=uint32 0

[wm/keybindings]
close=['<Super>q']

### DCONF-PATH /org/gnome/shell/keybindings/
[/]
screenshot=['<Control><Alt>s']
show-screenshot-ui=['<Shift><Control>s']

### DCONF-PATH /org/gnome/settings-daemon/
[plugins/color]
night-light-enabled=false
night-light-schedule-automatic=false

[plugins/housekeeping]
donation-reminder-last-shown=int64 1784101818281516

[plugins/media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']
home=['<Super>e']
reboot=['<Shift><Super>r']
shutdown=@as []
volume-down=['<Control>Down']
volume-up=['<Control>Up']

[plugins/media-keys/custom-keybindings/custom0]
binding='<Super>f'
command='firefox'
name='firefox'

[plugins/media-keys/custom-keybindings/custom1]
binding='<Super>Return'
command='ghostty'
name='ghostty'

[plugins/media-keys/custom-keybindings/custom2]
binding='<Shift><Super>v'
command='/home/yoge/.local/bin/copyninja pick'
name='Clipboard History'

[plugins/media-keys/custom-keybindings/custom3]
binding='<Shift><Super>p'
command='poweroff'
name='poweroff'

[plugins/media-keys/custom-keybindings/custom4]
binding='<Shift><Super>t'
command='restart'
name='restart'

[plugins/power]
idle-dim=false
power-button-action='interactive'
sleep-inactive-ac-type='nothing'
sleep-inactive-battery-type='nothing'

